import fs from 'node:fs';
import crypto from 'node:crypto';
import * as T from 'three';
import {GrandPiano as Baseline} from './base/piano.mjs';
import {GrandPiano as Candidate} from './candidate/piano.mjs';
import {Direction} from './base/direction.mjs';
globalThis.document={createElement:()=>({width:512,height:96,getContext:()=>new Proxy({},{get:()=>()=>{}})})};
const score=JSON.parse(fs.readFileSync('/workspace/sites/daybreak-piano-film/public/assets/score.json'));
const root=new URL('.',import.meta.url),baseline=new Baseline();
const disposed=new Set(),originalDispose=T.BufferGeometry.prototype.dispose;
T.BufferGeometry.prototype.dispose=function(){disposed.add(this);return originalDispose.call(this);};
const candidate=new Candidate();T.BufferGeometry.prototype.dispose=originalDispose;
const failures=[];
function materialSignature(m){const keys=['type','side','transparent','opacity','depthTest','depthWrite','blending','roughness','metalness','clearcoat','clearcoatRoughness','flatShading','vertexColors'];const result=Object.fromEntries(keys.map(k=>[k,m[k]]));for(const k of ['color','emissive'])if(m[k])result[k]=m[k].toArray();for(const k of ['map','normalMap','roughnessMap'])if(m[k])result[k]={path:m[k].userData.sourcePath,colorSpace:m[k].colorSpace,repeat:m[k].repeat.toArray(),offset:m[k].offset.toArray(),wrapS:m[k].wrapS,wrapT:m[k].wrapT};return JSON.stringify(result);}
function staticMeshes(piano){const skip=new Set();piano.pedals.forEach(o=>o.traverse(c=>skip.add(c)));const found=[];piano.group.updateMatrixWorld(true);piano.group.traverseVisible(o=>{if(o.isMesh&&!o.isInstancedMesh&&!o.material.transparent&&!skip.has(o))found.push(o);});return found;}
function triangles(piano){const records=new Map();let count=0;const p=new T.Vector3(),n=new T.Vector3(),nm=new T.Matrix3();for(const mesh of staticMeshes(piano)){const g=mesh.geometry,idx=g.index,normal=g.attributes.normal,uv=g.attributes.uv;nm.getNormalMatrix(mesh.matrixWorld);const signature=materialSignature(mesh.material)+'/'+[mesh.castShadow,mesh.receiveShadow,mesh.renderOrder,mesh.layers.mask].join('/');for(let i=0;i<(idx?.count??g.attributes.position.count);i+=3){const ps=[],ns=[],uvs=[];for(let corner=0;corner<3;corner++){const at=idx?idx.getX(i+corner):i+corner;p.fromBufferAttribute(g.attributes.position,at).applyMatrix4(mesh.matrixWorld);n.fromBufferAttribute(normal,at).applyMatrix3(nm).normalize();ps.push(...p.toArray());ns.push(...n.toArray());uvs.push(uv.getX(at),uv.getY(at));}const key=signature+'/'+ps.slice(0,3).map(x=>Math.floor(x*1e3)).join(',');const a=records.get(key)??[];a.push({ps,ns,uvs,signature});records.set(key,a);count++;}}return {records,count};}
const a=triangles(baseline),b=triangles(candidate);let maxPosition=0,maxNormal=0,maxUv=0,compared=0;
for(const left of a.records.values())for(const triangle of left){
 const cell=triangle.ps.slice(0,3).map(x=>Math.floor(x*1e3));let match=null;
 for(let dx=-1;dx<=1&&!match;dx++)for(let dy=-1;dy<=1&&!match;dy++)for(let dz=-1;dz<=1&&!match;dz++){
 const list=b.records.get(triangle.signature+'/'+[cell[0]+dx,cell[1]+dy,cell[2]+dz].join(','));
 if(list)for(const other of list){if(other.used)continue;const error=Math.max(...triangle.ps.map((x,i)=>Math.abs(x-other.ps[i])));if(error<=3e-7&&triangle.uvs.every((x,i)=>x===other.uvs[i])){match=other;break;}}
 }
 if(!match){failures.push({kind:'unmatched triangle',position:triangle.ps});continue;}
 match.used=true;maxPosition=Math.max(maxPosition,...triangle.ps.map((x,i)=>Math.abs(x-match.ps[i])));maxNormal=Math.max(maxNormal,...triangle.ns.map((x,i)=>Math.abs(x-match.ns[i])));maxUv=Math.max(maxUv,...triangle.uvs.map((x,i)=>Math.abs(x-match.uvs[i])));compared++;
}
const unused=[...b.records.values()].flat().filter(x=>!x.used).length;
if(a.count!==b.count||unused)failures.push({kind:'triangle count',a:a.count,b:b.count,unused});
if(maxPosition>3e-7||maxNormal>3e-7||maxUv!==0)failures.push({kind:'surface attribute difference',maxPosition,maxNormal,maxUv});
// Compare actual animated object matrices and contact values through the score.
let dynamicSnapshots=0,maxDynamicDifference=0;const fieldNames=['whiteKeyBatch','blackKeyBatch','damperCaps','damperFelts','damperStems'];
const times=[0,...score.notes.flatMap((n,i)=>i%4===0?[n.time-.015,n.time+n.duration*.5,n.time+n.duration+.04]:[]),...score.pedals.map(p=>p.time)];
for(const time of times){const pedal=.5+.5*Math.sin(time*.37);baseline.update(time,score.notes,pedal);candidate.update(time,score.notes,pedal);baseline.group.updateMatrixWorld(true);candidate.group.updateMatrixWorld(true);for(const field of fieldNames){const x=baseline[field].instanceMatrix.array,y=candidate[field].instanceMatrix.array;for(let i=0;i<x.length;i++)maxDynamicDifference=Math.max(maxDynamicDifference,Math.abs(x[i]-y[i]));}
for(const [midi,key] of baseline.keys){const other=candidate.keys.get(midi);if(other.mesh.visible)failures.push({kind:'visible audit mesh',midi});for(let j=0;j<16;j++)maxDynamicDifference=Math.max(maxDynamicDifference,Math.abs(key.mesh.matrixWorld.elements[j]-other.mesh.matrixWorld.elements[j]));maxDynamicDifference=Math.max(maxDynamicDifference,baseline.contact(midi).distanceTo(candidate.contact(midi)));}
for(let i=0;i<3;i++)for(let j=0;j<16;j++)maxDynamicDifference=Math.max(maxDynamicDifference,Math.abs(baseline.pedals[i].matrixWorld.elements[j]-candidate.pedals[i].matrixWorld.elements[j]));if(JSON.stringify(baseline.active)!==JSON.stringify(candidate.active))failures.push({kind:'active mismatch',time});dynamicSnapshots++;}
if(maxDynamicDifference!==0)failures.push({kind:'dynamic difference',maxDynamicDifference});
let liveDisposed=0;candidate.group.traverse(o=>{if(o.geometry&&disposed.has(o.geometry))liveDisposed++;});if(liveDisposed)failures.push({kind:'disposed live geometry',liveDisposed});
function bytes(piano){let metadataJsonBytes=0;piano.group.traverse(o=>{if(o.userData.sourceParts)metadataJsonBytes+=Buffer.byteLength(JSON.stringify(o.userData.sourceParts));});const geometries=new Set(),buffers=new Set();let vertices=0;const add=a=>{if(a)buffers.add(a.array.buffer)};piano.group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.isInstancedMesh){add(o.instanceMatrix);add(o.instanceColor);}});for(const g of geometries){vertices+=g.attributes.position?.count??0;for(const a of Object.values(g.attributes))add(a);add(g.index);}return {geometries:geometries.size,vertices,metadataJsonBytes,bufferBytes:[...buffers].reduce((n,b)=>n+b.byteLength,0)};}
// Installed Three r183's projectObject visibility/frustum/material rules. One
// InstancedMesh is one submission, independent of count. No GPU is mocked.
function submissions(piano,camera){piano.group.updateMatrixWorld(true);camera.updateMatrixWorld(true);const frustum=new T.Frustum().setFromProjectionMatrix(new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse));let calls=0,triangles=0,instanceCalls=0;const buckets=new Map();function visit(o){if(!o.visible)return;if(o.layers.test(camera.layers)&&(o.isMesh||o.isLine||o.isPoints)&&(!o.frustumCulled||frustum.intersectsObject(o))){const mats=Array.isArray(o.material)?o.geometry.groups.map(g=>[o.material[g.materialIndex],g]):[[o.material,null]];for(const [material,group] of mats){if(!material?.visible)continue;calls++;if(o.isInstancedMesh)instanceCalls++;const key=materialSignature(material);buckets.set(key,(buckets.get(key)??0)+1);if(o.isMesh)triangles+=(group?.count??o.geometry.index?.count??o.geometry.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);}}o.children.forEach(visit);}visit(piano.group);return {calls,triangles,instanceCalls,materialBuckets:buckets.size};}
const direction=new Direction(score),camera=new T.PerspectiveCamera(40,16/9,.035,180),draws=[];
for(const aspect of [16/9,9/16])for(const [shotIndex,shot] of direction.shots.entries())for(const fraction of [.08,.5,.92]){const time=shot.start+(shot.end-shot.start)*fraction;camera.aspect=aspect;direction.update(camera,time,aspect);const base=submissions(baseline,camera),cand=submissions(candidate,camera);draws.push({shotIndex,shot:shot.name,time,aspect,baseline:base,candidate:cand});if(cand.calls>=base.calls)failures.push({kind:'no submission improvement',shotIndex,fraction,aspect,base,cand});}
const reduce=key=>{const values=draws.map(d=>d[key].calls);return {min:Math.min(...values),max:Math.max(...values),mean:values.reduce((a,b)=>a+b,0)/values.length}};
const geoBefore=bytes(baseline),geoAfter=bytes(candidate),report={passed:failures.length===0,sourceHashes:Object.fromEntries(['base','candidate'].map(v=>[v,crypto.createHash('sha256').update(fs.readFileSync(new URL(v+'/piano.ts',root))).digest('hex')])),static:{before:staticMeshes(baseline).length,after:staticMeshes(candidate).length,triangles:a.count,compared,maxPositionErrorMm:maxPosition*1000,maxNormalComponentError:maxNormal,maxUvError:maxUv},dynamic:{snapshots:dynamicSnapshots,hiddenAuditKeys:candidate.keys.size,maxDifference:maxDynamicDifference},disposal:{constructionDisposedGeometries:disposed.size,reachableDisposedGeometries:liveDisposed},memory:{before:geoBefore,after:geoAfter,deltaBytes:geoAfter.bufferBytes-geoBefore.bufferBytes},mainPass:{views:draws.length,before:reduce('baseline'),after:reduce('candidate'),meanTriangleIncrease:draws.reduce((n,d)=>n+d.candidate.triangles-d.baseline.triangles,0)/draws.length,scope:'Three r183 structural main-pass submission counts after actual frustum culling, not measured browser renderer.info or timing; seven instance batches count once each.'},failures};fs.writeFileSync(new URL('verification.json',root),JSON.stringify(report,null,2));fs.writeFileSync(new URL('draw-views.json',root),JSON.stringify(draws,null,2));console.log(JSON.stringify({...report,failures:report.failures.slice(0,5),failureCount:report.failures.length},null,2));if(!report.passed)process.exitCode=1;
