import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
for(const file of ['input-hashes.json','hashes.json'])for(const [p,h]of Object.entries(read(file)))assert.equal(sha(p),h,p);
const audit=read('baseline-audit.json'),queue=read('bad-note-queue.json'),fit=read('fit-report.json'),v=read('validation-report.json'),changes=read('changes.json');
assert.equal(audit.rows.length,289);assert.equal(audit.samples,3757);assert.equal(queue.length,153);assert.equal(queue.filter(r=>r.reserved).length,13);assert.equal(fit.filter(r=>r.status==='accepted').length,71);assert.equal(fit.filter(r=>r.status==='exception').length,69);assert.equal(changes.length,71);assert.equal(v.samples,8857);assert.equal(v.changedSamples,4900);assert.equal(v.failedChanges.length,0);assert.equal(v.newFailures.length,0);assert.equal(v.rows.filter(r=>r.summary.bad).length,82);assert.equal(v.candidateSha256,sha('candidate-score.json'));
for(const r of v.rows.filter(r=>r.changed)){assert.ok(r.summary.keyCore<=3);assert.ok(r.summary.minimumPadGap>=-2.5);assert.ok(r.summary.maximumPadGap<=2.5);assert.equal(r.summary.missingPad,0);assert.equal(r.summary.ownPairs,0);assert.equal(r.summary.neighborPairs,0);}
const a=read('baseline-score.json'),b=read('candidate-score.json'),reservation=read('reservations.json'),reserved=new Set([...reservation.root,...reservation.activeLowSupport,...reservation.activeAddedNeighbors,...reservation.activeWholeGrips.flatMap(r=>r.ids)]);assert.equal(reserved.size,72);
for(let i=0;i<a.notes.length;i++){if(reserved.has(a.notes[i].id))assert.deepEqual(a.notes[i],b.notes[i]);for(const key of ['contactZ','contactLift','thumbOpposition']){delete a.notes[i][key];delete b.notes[i][key];}}assert.deepEqual(a,b);assert.deepEqual(read('candidate-score.json'),read('merge-check-score.json'));
const transitions=read('root-transition-queue.json');assert.equal(transitions.transitions.length,119);assert.equal(transitions.paired.length,71);assert.equal(read('whole-grip-exceptions.json').length,69);
const evidence=read('evidence-manifest.json');let frames=0;for(const render of evidence.renders){assert.equal(sha(render.report),render.sha256);for(const frame of render.frames){assert.equal(sha(frame.image),frame.sha256);assert.equal(frame.glError,'GL_NO_ERROR');frames++;}}assert.equal(frames,6);
console.log('PASS: 289 thumbs audited; 71 held fixes pass 8857 geometry samples; 69 explicit exceptions; 13 reserved failures; 119 idle transitions queued; 6 exact render frames.');
