import {T,body,piano,performer,measure,isBlack,baseline} from './harness.mjs';
export const heldFractions=[.001,.02,.05,.125,.25,.375,.5,.625,.75,.875,.95,.98,.999];
const a=body.geometry.attributes;
const pads=Object.fromEntries(['L','R'].map(side=>{const ids=[];for(let i=0;i<a.position.count;i++){let w=0;for(let j=0;j<4;j++)if(body.skeleton.bones[a.skinIndex.getComponent(i,j)].name===(side==='L'?'Left':'Right')+'HandThumb3')w+=a.skinWeight.getComponent(i,j);if(w>.65)ids.push(i);}return[side,ids];}));
export function sample(note,time){
 const r=measure(time,note.hand,{targetFinger:1});
 const key=piano.keys.get(note.midi),box=key.mesh.geometry.boundingBox,inverse=key.mesh.matrixWorld.clone().invert(),bevel=isBlack(note.midi)?.002:.0014;
 let padGap=Infinity,padVertex=null,padCount=0,padPoint=null;
 for(const id of pads[note.hand]){const world=body.getVertexPosition(id,new T.Vector3()).applyMatrix4(body.matrixWorld),p=world.clone().applyMatrix4(inverse);if(p.x<box.min.x+bevel||p.x>box.max.x-bevel||p.z<box.min.z+bevel||p.z>box.max.z-bevel)continue;padCount++;const gap=(p.y-box.max.y)*1000;if(gap<padGap){padGap=gap;padVertex=id;padPoint=world.toArray();}}
 const thumbKeyHits=r.keyHits.filter(h=>h.patch===note.hand+'Thumb'),palmKeyHits=r.keyHits.filter(h=>h.patch===note.hand+'Palm'),keyCore=Math.max(0,...thumbKeyHits.map(h=>h.depth),...palmKeyHits.map(h=>h.depth));
 const own=r.crossings.filter(c=>c.a===note.hand+'Palm'||c.b===note.hand+'Palm'),neighbor=r.crossings.filter(c=>c.a!==note.hand+'Palm'&&c.b!==note.hand+'Palm');
 return{time,fraction:(time-note.time)/note.duration,keyCore,thumbKeyCore:Math.max(0,...thumbKeyHits.map(h=>h.depth)),palmKeyCore:Math.max(0,...palmKeyHits.map(h=>h.depth)),padGap:Number.isFinite(padGap)?padGap:null,padCount,padVertex,padPoint,surfaceGap:r.meshContacts.find(c=>c.id===note.id)?.minGap??null,pointContactMm:Math.max(0,...r.contacts.filter(c=>c.finger===1).map(c=>c.error*1000)),ownPairs:own.reduce((n,c)=>n+c.trianglePairs,0),neighborPairs:neighbor.reduce((n,c)=>n+c.trianglePairs,0),keyHits:[...thumbKeyHits,...palmKeyHits],crossings:r.crossings.map(c=>({...c,points:c.points.slice(0,2)}))};
}
export function summarize(samples){const summary={keyCore:Math.max(0,...samples.map(r=>r.keyCore)),thumbKeyCore:Math.max(0,...samples.map(r=>r.thumbKeyCore)),palmKeyCore:Math.max(0,...samples.map(r=>r.palmKeyCore)),minimumPadGap:Math.min(...samples.map(r=>r.padGap??Infinity)),maximumPadGap:Math.max(...samples.map(r=>r.padGap??-Infinity)),missingPad:samples.filter(r=>r.padGap===null).length,ownPairs:Math.max(0,...samples.map(r=>r.ownPairs)),neighborPairs:Math.max(0,...samples.map(r=>r.neighborPairs)),pointContactMm:Math.max(0,...samples.map(r=>r.pointContactMm))};summary.bad=summary.keyCore>3||summary.minimumPadGap< -2.5||summary.maximumPadGap>2.5||summary.missingPad>0||summary.ownPairs>0||summary.neighborPairs>0;return summary;}
export function heldTimes(n,dense=false){const times=heldFractions.map(u=>n.time+n.duration*u);if(dense){const start=n.time+Math.min(.0001,n.duration*.001),end=n.time+n.duration-Math.min(.0001,n.duration*.001);for(let t=start;t<=end;t+=1/120)times.push(t);times.push(end);}return [...new Set(times.map(t=>+t.toFixed(8)))].sort((a,b)=>a-b);}
