import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {baseline,install} from './harness.mjs';
import {sample,summarize,heldTimes} from './metric.mjs';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),candidate=JSON.parse(fs.readFileSync('candidate-score.json')),fit=JSON.parse(fs.readFileSync('fit-report.json')),rows=[],changes=[];
const r=JSON.parse(fs.readFileSync('reservations.json')),reserved=new Set([...r.root,...r.activeLowSupport,...(r.activeAddedNeighbors??[]),...r.activeWholeGrips.flatMap(g=>g.ids)]);
const allowed=new Set(['contactZ','contactLift','thumbOpposition']);
const oldCore=structuredClone(baseline),newCore=structuredClone(candidate);
assert.equal(oldCore.notes.length,newCore.notes.length);
for(let i=0;i<baseline.notes.length;i++){const before=baseline.notes[i],after=candidate.notes[i];assert.equal(before.id,after.id);const fields=[...new Set([...Object.keys(before),...Object.keys(after)])].filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k]));if(fields.length){assert.ok(!reserved.has(before.id));assert.equal(before.finger,1);assert.ok(fields.every(k=>allowed.has(k)));changes.push({id:before.id,time:before.time,duration:before.duration,hand:before.hand,midi:before.midi,fields,before:Object.fromEntries(fields.map(k=>[k,before[k]??null])),after:Object.fromEntries(fields.map(k=>[k,after[k]??null]))});}for(const f of allowed){delete oldCore.notes[i][f];delete newCore.notes[i][f];}}
assert.deepEqual(oldCore,newCore);assert.equal(changes.length,fit.filter(r=>r.status==='accepted').length);
install(candidate);const changed=new Set(changes.map(c=>c.id));
for(const note of candidate.notes.filter(n=>n.finger===1)){const samples=heldTimes(note,changed.has(note.id)).map(t=>sample(note,t));rows.push({id:note.id,changed:changed.has(note.id),summary:summarize(samples),samples});if(rows.length%40===0)console.log('validated',rows.length);}
const originals=JSON.parse(fs.readFileSync('baseline-audit.json')).rows,newFailures=rows.filter(r=>r.summary.bad&&!originals.find(o=>o.note.id===r.id).summary.bad),failedChanges=rows.filter(r=>r.changed&&r.summary.bad);
const transitions=[];for(const c of changes){const same=candidate.notes.filter(n=>n.hand===c.hand&&n.finger===1),idx=same.findIndex(n=>n.id===c.id),prev=same[idx-1],next=same[idx+1],note=same[idx];for(const [a,b]of [[prev,note],[note,next]])if(a&&b)transitions.push({hand:c.hand,from:a.id,to:b.id,fromRelease:a.time+a.duration,toAttack:b.time,gap:b.time-a.time-a.duration,reviewStart:Math.max(0,Math.min(a.time+a.duration,b.time)-.12),reviewEnd:Math.max(a.time+a.duration,b.time)+.12,reason:'Changed held endpoint changes compact5 idle thumb interpolation; root must recheck actual geometry and continuity.'});}
const unique=[...new Map(transitions.map(t=>[t.hand+':'+t.from+':'+t.to,t])).values()],paired=changes.map(c=>({id:c.id,attack:c.time,release:c.time+c.duration,nearbyOppositeEvents:candidate.notes.filter(n=>n.hand!==c.hand&&(Math.abs(n.time-c.time)<.12||Math.abs(n.time+n.duration-c.time-c.duration)<.12)).map(n=>({id:n.id,attack:n.time,release:n.time+n.duration,finger:n.finger})),reason:'Timing is unchanged; root must review paired articulation and updated endpoint transitions in combined score.'}));
const report={baselineSha256:sha(fs.readFileSync('baseline-score.json')),candidateSha256:sha(fs.readFileSync('candidate-score.json')),allThumbs:rows.length,samples:rows.reduce((n,r)=>n+r.samples.length,0),changes:changes.length,changedSamples:rows.filter(r=>r.changed).reduce((n,r)=>n+r.samples.length,0),unauthorizedChanges:0,newFailures:newFailures.map(r=>r.id),failedChanges:failedChanges.map(r=>r.id),rows};
fs.writeFileSync('changes.json',JSON.stringify(changes,null,2));fs.writeFileSync('validation-report.json',JSON.stringify(report,null,2));fs.writeFileSync('root-transition-queue.json',JSON.stringify({transitions:unique,paired},null,2));
const exceptions=fit.filter(r=>r.status==='exception').map(r=>({id:r.id,note:r.original,before:r.before,best:r.best,trials:r.tried,reason:r.reason}));fs.writeFileSync('whole-grip-exceptions.json',JSON.stringify(exceptions,null,2));
assert.equal(newFailures.length,0);assert.equal(failedChanges.length,0);console.log(JSON.stringify({PASS:true,allThumbs:rows.length,changedNotes:changes.length,samples:report.samples,changedSamples:report.changedSamples,exceptions:exceptions.length,newFailures:0,unauthorizedChanges:0,transitions:unique.length,paired:paired.length}));
