import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { pathToFileURL } from 'node:url';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { GrandPiano } from './compiled/piano.mjs';
// Isolated rig candidates can use the same real scene and material renderer.
const rigPath=path.resolve(process.env.DAYBREAK_RIG_PATH??'production/qa/compiled/pianist.mjs');
const { Pianist }=await import(pathToFileURL(rigPath));
import { Stage } from './compiled/stage.mjs';
import { PERFORMANCE_LOOK } from './compiled/render-settings.mjs';
import { Direction } from './compiled/direction.mjs';
import { pedalPosition, mix, smooth } from './compiled/math.mjs';
const qaRoot=process.env.DAYBREAK_QA_ROOT??path.resolve('work/render-qa');fs.mkdirSync(qaRoot,{recursive:true});
const inputPaths={rig:rigPath,score:path.resolve(process.env.DAYBREAK_SCORE_PATH??'public/assets/score.json'),model:path.resolve(process.env.DAYBREAK_MODEL_PATH??'public/assets/pianist.glb'),piano:path.resolve('production/qa/compiled/piano.mjs'),stage:path.resolve('production/qa/compiled/stage.mjs'),direction:path.resolve('production/qa/compiled/direction.mjs'),look:path.resolve('production/qa/compiled/render-settings.mjs')};
if(process.env.DAYBREAK_CORRECTOR_PATH)inputPaths.corrector=path.resolve(process.env.DAYBREAK_CORRECTOR_PATH);
const renderInputs={files:Object.fromEntries(Object.entries(inputPaths).map(([name,file])=>[name,{file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')}])),aspect:Number(process.env.DAYBREAK_ASPECT??16/9),shot:Number(process.env.DAYBREAK_SHOT??-1),detail:process.env.DAYBREAK_DETAIL??null};
fs.writeFileSync(path.join(qaRoot,'scene-inputs.json'),JSON.stringify(renderInputs,null,2)+'\n');
const ctx=new Proxy({canvas:null},{get:(t,k)=>k in t?t[k]:(...args)=>{}});
globalThis.document={createElement:(type)=>({width:512,height:512,getContext:()=>ctx})};globalThis.window={devicePixelRatio:1};globalThis.self=globalThis;
const data=fs.readFileSync(process.env.DAYBREAK_MODEL_PATH??'public/assets/pianist.glb');const jsonLength=data.readUInt32LE(12);const modelJson=JSON.parse(data.subarray(20,20+jsonLength).toString());const binOffset=20+jsonLength+8;const bin=data.subarray(binOffset);
const texPaths=[];for(let i=0;i<(modelJson.images??[]).length;i++){const im=modelJson.images[i];if(im.bufferView!==undefined){const bv=modelJson.bufferViews[im.bufferView];const p=path.join(qaRoot,`texture-${i}.${im.mimeType==='image/png'?'png':'jpg'}`);fs.writeFileSync(p,bin.subarray(bv.byteOffset??0,(bv.byteOffset??0)+bv.byteLength));texPaths.push(p);}else texPaths.push('');}
const loader=new GLTFLoader();loader.register(parser=>({name:'offline-texture-reference',loadTexture:(idx)=>{const tx=new THREE.Texture();tx.flipY=false;tx.userData.sourcePath=texPaths[parser.json.textures[idx].source];return Promise.resolve(tx);}}));
const gltf=await loader.parseAsync(data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),'');const score=JSON.parse(fs.readFileSync(process.env.DAYBREAK_SCORE_PATH??'public/assets/score.json'));
const scene=new THREE.Scene();const piano=new GrandPiano();const stage=new Stage(scene,false);const pianist=new Pianist();scene.add(piano.group,pianist.group);await pianist.load(score,gltf.scene);const direction=new Direction(score);const aspect=Number(process.env.DAYBREAK_ASPECT??16/9);const camera=new THREE.PerspectiveCamera(40,aspect,.03,180);
let volumeCorrector;
if(inputPaths.corrector){
 const {createWristVolumeCorrector}=await import(pathToFileURL(inputPaths.corrector));let body;
 gltf.scene.traverse(object=>{if(object.isSkinnedMesh&&object.name==='Human')body=object;});
 if(!body)throw new Error('Wrist candidate requires the actual Human skinned mesh.');
 volumeCorrector=createWristVolumeCorrector(THREE,body,{rollForearm:true,smoothWeights:8});
}
stage.update(0,score.sections[0].energy,0);
const out={time:0,shot:'',camera:{matrix:camera.matrixWorld.toArray(),fov:camera.fov,aspect},meshes:[],lines:[],points:[],lights:[],materials:[]};out.renderSettings={fogColor:new THREE.Color(PERFORMANCE_LOOK.fogColor).toArray(),fogDensity:PERFORMANCE_LOOK.fogDensity,toneMappingExposure:PERFORMANCE_LOOK.exposure,environmentIntensity:PERFORMANCE_LOOK.environmentIntensity};out.environmentCapture={lift:stage.sky.uniforms.uLift.value,position:PERFORMANCE_LOOK.environmentPosition,size:PERFORMANCE_LOOK.environmentSize,lightIntensities:[...stage.lights.map(l=>l.intensity),stage.accent.intensity]};const materials=new Map(),materialRefs=[],meshRefs=[],lightRefs=[];
function matIndex(mat){if(materials.has(mat.uuid))return materials.get(mat.uuid);const i=out.materials.length;materials.set(mat.uuid,i);materialRefs.push(mat);out.materials.push({name:mat.name,basic:!!mat.isMeshBasicMaterial,emissiveIntensity:mat.emissiveIntensity??1,color:mat.color?.toArray()??[.3,.35,.4],roughness:mat.roughness??.5,metalness:mat.metalness??0,clearcoat:mat.clearcoat??0,clearcoatRoughness:mat.clearcoatRoughness??0,envMapIntensity:mat.envMapIntensity??1,mapFlipY:mat.map?.flipY??false,normalFlipY:mat.normalMap?.flipY??false,mapAnisotropy:mat.map?.anisotropy??1,normalAnisotropy:mat.normalMap?.anisotropy??1,alpha:mat.opacity??1,map:mat.map?.userData.sourcePath??null,normal:mat.normalMap?.userData.sourcePath??null,normalScale:mat.normalScale?.toArray()??[1,1],uvRepeat:mat.map?.repeat.toArray()??[1,1],uvOffset:mat.map?.offset.toArray()??[0,0],alphaTest:mat.alphaTest??0,emissive:mat.isMeshBasicMaterial?mat.color?.toArray()??[0,0,0]:mat.emissive?.toArray()??[0,0,0],doubleSided:mat.side===THREE.DoubleSide});return i;}
function verts(mesh){const a=new Float32Array(mesh.geometry.attributes.position.count*3),v=new THREE.Vector3();for(let i=0;i<a.length/3;i++){mesh.getVertexPosition(i,v);a.set(v.toArray(),i*3);}return a;}
function normals(mesh){const geom=mesh.geometry,n=geom.attributes.normal;if(!n)return null;const a=new Float32Array(n.count*3),v=new THREE.Vector3(),base=new THREE.Vector3(),m=new THREE.Vector3();const temp=new THREE.Matrix4(),blend=new THREE.Matrix4(),normalMatrix=new THREE.Matrix3();for(let i=0;i<n.count;i++){v.fromBufferAttribute(n,i);base.copy(v);for(let j=0;j<(geom.morphAttributes.normal?.length??0);j++){const influence=mesh.morphTargetInfluences?.[j]??0;if(influence){m.fromBufferAttribute(geom.morphAttributes.normal[j],i);if(!geom.morphTargetsRelative)m.sub(base);v.addScaledVector(m,influence);}}if(mesh.isSkinnedMesh){blend.elements.fill(0);const ids=geom.attributes.skinIndex,ws=geom.attributes.skinWeight;for(let j=0;j<4;j++){const bone=ids.array[i*4+j],weight=ws.array[i*4+j];if(!weight)continue;temp.fromArray(mesh.skeleton.boneMatrices,bone*16);for(let k=0;k<16;k++)blend.elements[k]+=temp.elements[k]*weight;}blend.multiply(mesh.bindMatrix).premultiply(mesh.bindMatrixInverse);normalMatrix.setFromMatrix4(blend);v.applyMatrix3(normalMatrix);}v.normalize();a.set(v.toArray(),i*3);}return a;}
function inStage(mesh){for(let p=mesh;p;p=p.parent)if(p===stage.group)return true;return !!mesh.userData.qaStage;}
function writeMesh(mesh,matrix,instance=-1){const geom=mesh.geometry;if(!geom.attributes.position)return;const material=Array.isArray(mesh.material)?mesh.material:[mesh.material];if(material.some(m=>m.isShaderMaterial||m.map?.isCanvasTexture&&m.transparent&&!m.map.userData.sourcePath))return;meshRefs.push({mesh,instance});out.meshes.push({stage:inStage(mesh),castShadow:mesh.castShadow,receiveShadow:mesh.receiveShadow,name:mesh.name+'_'+meshRefs.length,vertices:Array.from(verts(mesh)),normals:Array.from(normals(mesh)??[]),indices:geom.index?Array.from(geom.index.array):Array.from({length:geom.attributes.position.count},(_,i)=>i),uvs:geom.attributes.uv?Array.from(geom.attributes.uv.array):null,colors:geom.attributes.color?Array.from(geom.attributes.color.array):null,matrix:matrix.toArray(),materials:material.map(matIndex),groups:geom.groups,smooth:!material[0].flatShading,deformed:mesh.isSkinnedMesh||!!mesh.morphTargetInfluences});}
function writeInstanceBatch(mesh){
 const source=mesh.geometry,vertices=source.attributes.position.count,total=vertices*mesh.count,positions=new Float32Array(total*3),ns=new Float32Array(total*3),uvs=new Float32Array(total*2),colors=new Float32Array(total*3),baseIndices=source.index?source.index.array:Array.from({length:vertices},(_,i)=>i),indices=new Uint32Array(baseIndices.length*mesh.count),m=new THREE.Matrix4(),nmat=new THREE.Matrix3(),v=new THREE.Vector3(),n=new THREE.Vector3(),color=new THREE.Color(1,1,1);
 for(let i=0;i<mesh.count;i++){
 mesh.getMatrixAt(i,m);m.premultiply(mesh.matrixWorld);nmat.getNormalMatrix(m);if(mesh.instanceColor)mesh.getColorAt(i,color);
 for(let k=0;k<vertices;k++){
 v.fromBufferAttribute(source.attributes.position,k).applyMatrix4(m);positions.set(v.toArray(),(i*vertices+k)*3);
 if(source.attributes.normal){n.fromBufferAttribute(source.attributes.normal,k).applyMatrix3(nmat).normalize();ns.set(n.toArray(),(i*vertices+k)*3);}
 if(source.attributes.uv)uvs.set([source.attributes.uv.getX(k),source.attributes.uv.getY(k)],(i*vertices+k)*2);
 colors.set(color.toArray(),(i*vertices+k)*3);
 }
 for(let k=0;k<baseIndices.length;k++)indices[i*baseIndices.length+k]=i*vertices+baseIndices[k];
 }
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('normal',new THREE.BufferAttribute(ns,3));geometry.setAttribute('uv',new THREE.BufferAttribute(uvs,2));geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.setIndex(new THREE.BufferAttribute(indices,1));
 const batch=new THREE.Mesh(geometry,mesh.material);batch.name=mesh.name+' static batch';batch.userData.qaStage=inStage(mesh);batch.castShadow=mesh.castShadow;batch.receiveShadow=mesh.receiveShadow;batch.updateMatrixWorld();writeMesh(batch,batch.matrixWorld);
}
function update(time){let index=score.sections.findIndex(s=>time>=s.start&&time<s.end);if(index<0)index=score.sections.length-1;const section=score.sections[index],previous=score.sections[Math.max(0,index-1)],energy=mix(previous.energy,section.energy,smooth((time-section.start)/1.8));const pedal=pedalPosition(time,score.pedals);let pulse=0;for(const a of score.accents){const dt=time-a.time;if(dt>=0&&dt<1)pulse=Math.max(pulse,a.energy*Math.exp(-dt*5));}piano.update(time,score.notes,pedal);pianist.update(time,score,piano,pedal,energy);stage.update(time,energy,pulse);direction.override=Number(process.env.DAYBREAK_SHOT??-1);direction.update(camera,time,aspect);if(process.env.DAYBREAK_DETAIL==='hands'){camera.position.set(.42,1.32,.37);camera.lookAt(.00,.765,.245);camera.fov=42;camera.updateProjectionMatrix();}if(process.env.DAYBREAK_DETAIL==='portraitHands'){camera.position.set(.55,2.35,.88);camera.lookAt(0,.82,.23);camera.fov=45;camera.updateProjectionMatrix();}if(process.env.DAYBREAK_DETAIL==='pedal'){camera.position.set(.52,.38,.87);camera.lookAt(.045,.12,.28);camera.fov=42;camera.updateProjectionMatrix();}if(process.env.DAYBREAK_DETAIL==='piano'){camera.position.set(1.72,2.66,.85);camera.lookAt(0,.83,-.82);camera.fov=47;camera.updateProjectionMatrix();}if(process.env.DAYBREAK_DETAIL==='sideHands'){camera.position.set(.98,.96,.43);camera.lookAt(0,.78,.25);camera.fov=42;camera.updateProjectionMatrix();}if(process.env.DAYBREAK_DETAIL==='sleeve'){camera.position.set(-1.45,1.35,.85);camera.lookAt(0,1.00,.60);camera.fov=40;camera.updateProjectionMatrix();}if(process.env.DAYBREAK_DETAIL==='face'){camera.position.set(.43,1.46,-.12);camera.lookAt(0,1.23,.62);camera.fov=30;camera.updateProjectionMatrix();}scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);scene.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update();});volumeCorrector?.update();return energy;}
update(0);
scene.traverse(o=>{if(!o.visible)return;if(o.isHemisphereLight)out.hemisphere={skyColor:o.color.toArray(),groundColor:o.groundColor.toArray(),direction:o.position.clone().normalize().toArray(),intensity:o.intensity};if(o.isLineSegments){out.lines.push({name:o.name,vertices:Array.from(o.geometry.attributes.position.array),colors:o.geometry.attributes.color?Array.from(o.geometry.attributes.color.array):null,indices:o.geometry.index?Array.from(o.geometry.index.array):null,matrix:o.matrixWorld.toArray(),color:o.material.color?.toArray()??[1,1,1],opacity:o.material.opacity??1,vertexColors:!!o.material.vertexColors});}if(o.isPoints){out.points.push({name:o.name,vertices:Array.from(o.geometry.attributes.position.array),sizes:o.geometry.attributes.aSize?Array.from(o.geometry.attributes.aSize.array):null,seeds:o.geometry.attributes.aSeed?Array.from(o.geometry.attributes.aSeed.array):null,matrix:o.matrixWorld.toArray()});}if(o.isLight&&!o.isHemisphereLight){out.lights.push({type:o.type,distance:o.distance,decay:o.decay,color:o.color.toArray(),intensity:o.intensity,position:o.getWorldPosition(new THREE.Vector3()).toArray(),target:o.target?.getWorldPosition(new THREE.Vector3()).toArray()??null,angle:o.angle,penumbra:o.penumbra});lightRefs.push(o);}if(o.isMesh){if(o.isInstancedMesh&&o.count>250){writeInstanceBatch(o);}else if(o.isInstancedMesh){const m=new THREE.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,m);writeMesh(o,o.matrixWorld.clone().multiply(m),i);}}else writeMesh(o,o.matrixWorld);}});
out.camera={matrix:camera.matrixWorld.toArray(),fov:camera.fov,aspect};out.shot=direction.name;
const sceneTemp=qaRoot+'/scene-'+process.pid+'.tmp';fs.writeFileSync(sceneTemp,JSON.stringify(out));fs.renameSync(sceneTemp,qaRoot+'/scene.json');
process.stdout.write(JSON.stringify({ready:true,scene:qaRoot+'/scene.json',meshes:out.meshes.length,deformed:out.meshes.filter(m=>m.deformed).length,duration:score.duration})+'\n');
const {createInterface}=await import('node:readline');const rl=createInterface({input:process.stdin});
for await(const line of rl){const time=Number(line);if(!Number.isFinite(time))continue;const energy=update(time);const states=meshRefs.map(({mesh,instance},i)=>{let matrix=mesh.matrixWorld;if(instance>=0){const m=new THREE.Matrix4();mesh.getMatrixAt(instance,m);matrix=matrix.clone().multiply(m);}const s={matrix:matrix.toArray()};if(out.meshes[i].deformed){const a=verts(mesh);s.vertices=Buffer.from(a.buffer).toString('base64');const n=normals(mesh);if(n)s.normals=Buffer.from(n.buffer).toString('base64');}return s;});process.stdout.write(JSON.stringify({time,energy,pedal:pedalPosition(time,score.pedals),contacts:pianist.contacts,activeNotes:piano.active,shot:direction.name,camera:{matrix:camera.matrixWorld.toArray(),fov:camera.fov,aspect},meshes:states,lights:lightRefs.map(l=>l.intensity),emissive:materialRefs.map(m=>m.isMeshBasicMaterial?m.color?.toArray()??[0,0,0]:m.emissive?.toArray()??[0,0,0])})+'\n');}
