import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {runtime,T} from './runtime.mjs';
import {expectedReleaseWindows,assertCoverage} from './coverage.mjs';
const dir=process.argv[2],base=process.argv[3],windows=JSON.parse(fs.readFileSync(`${dir}/windows.json`)),times=JSON.parse(fs.readFileSync(`${dir}/times.json`)),oldScore=JSON.parse(fs.readFileSync(`${base}/score.json`)),newScore=JSON.parse(fs.readFileSync(`${dir}/score.json`)),stripped=structuredClone(newScore),ids=['db00083','db00346','db00390','db00408','db00509','db00520','db00666','db00681','db00739','db00847','db00862','db00920'],names=['Thumb','Index','Middle','Ring','Pinky'];
const coverage=assertCoverage(expectedReleaseWindows(oldScore,ids),windows,times);
for(const note of stripped.notes)if(ids.includes(note.id)){const profile=note.releaseTravel;assert.deepEqual(note.releaseWaypoint,{enabled:true,height:profile.height,x:profile.x??0,z:profile.z??0,liftEnd:profile.liftEnd??1/3,landStart:profile.landStart??2/3,roll:profile.roll??0,duration:profile.duration??.160});delete note.releaseWaypoint;}
assert.deepEqual(stripped,oldScore,'Non-waypoint fitted/audible fields changed');assert.equal(fs.readFileSync(`${base}/compiled/pianist.mjs`,'utf8'),fs.readFileSync(`${dir}/compiled/pianist.mjs`,'utf8'),'Shared runtime changed');
for(const [variant,prefix]of [[base,'baseline-'],[dir,'']]){
 execFileSync(process.execPath,['audit-hand-surfaces.mjs','--project','../pianopiece-threejs','--rig',`${variant}/compiled/pianist.mjs`,'--piano',`${variant}/compiled/piano.mjs`,'--score',`${variant}/score.json`,'--out',`${dir}/${prefix}surfaces.json`,'--times',`${dir}/times.json`],{stdio:'pipe'});
 execFileSync(process.execPath,['motion-batch.mjs',variant,`${dir}/windows.json`,`${dir}/${prefix}motion.json`],{stdio:'pipe'});
}
execFileSync(process.execPath,['compare-batch.mjs',dir],{stdio:'pipe'});
const comparison=JSON.parse(fs.readFileSync(`${dir}/comparison.json`)),before=JSON.parse(fs.readFileSync(`${dir}/baseline-surfaces.json`)),after=JSON.parse(fs.readFileSync(`${dir}/surfaces.json`)),motion=JSON.parse(fs.readFileSync(`${dir}/motion.json`));assert.deepEqual([...comparison.accepted].sort(),[...ids].sort());assert.equal(comparison.rejected.length,0);assert.equal(motion.failures.length,0);assert.equal(after.summary.nonfinite,0);
const a=await runtime(base),b=await runtime(dir);let quaternionError=0,endpointSkinError=0,heldSkinError=0;
const skinError=()=>{let max=0;for(let i=0;i<a.body.geometry.attributes.position.count;i++){const p=a.body.getVertexPosition(i,new T.Vector3()).applyMatrix4(a.body.matrixWorld),q=b.body.getVertexPosition(i,new T.Vector3()).applyMatrix4(b.body.matrixWorld);max=Math.max(max,p.distanceTo(q));}return max;};
for(const time of times){const win=windows.find(w=>time>=w.start-.025001&&time<=w.end+.025001);assert.ok(win);const allowed=new Set([1,2,3].map(j=>(win.hand==='L'?'Left':'Right')+'Hand'+names[win.finger-1]+j));a.pose(time);b.pose(time);for(let i=0;i<a.body.skeleton.bones.length;i++){const old=a.body.skeleton.bones[i],cur=b.body.skeleton.bones[i];assert.equal(old.name,cur.name);if(!allowed.has(old.name))for(let j=0;j<4;j++)quaternionError=Math.max(quaternionError,Math.abs(old.quaternion.toArray()[j]-cur.quaternion.toArray()[j]));}}
for(const win of windows){for(const t of [win.start-.00001,win.end,win.end+.00001]){a.pose(t);b.pose(t);endpointSkinError=Math.max(endpointSkinError,skinError());}const n=oldScore.notes.find(n=>n.id===win.id);for(const f of [.015,.25,.5,.8,.985]){const t=n.time+n.duration*f;a.pose(t);b.pose(t);heldSkinError=Math.max(heldSkinError,skinError());}}
assert.ok(quaternionError<1e-14);assert.ok(endpointSkinError<1e-12);assert.ok(heldSkinError<1e-12);
const inputs=[`${dir}/app/performance/pianist.ts`,`${dir}/compiled/pianist.mjs`,`${base}/score.json`,`${dir}/score.json`,'../pianopiece-threejs/public/assets/pianist.glb','audit-hand-surfaces.mjs','runtime.mjs','hand-shape.mjs','motion-validity.mjs','coverage.mjs','motion-batch.mjs','compare-batch.mjs','verify-routes.mjs',`${dir}/windows.json`,`${dir}/times.json`];
const report={passed:true,coverage,candidate:dir,baseline:base,scope:`${windows.length} isolated selected finite release intervals, ${times.length} actual-skin times, ${motion.samples} uniform240Hz motion times. Selected improvements only; remaining inherited full-song failures remain.`,invariants:{quaternionError,endpointSkinErrorMm:endpointSkinError*1000,heldSkinErrorMm:heldSkinError*1000},before:before.summary,after:after.summary,motion:{...motion,rows:undefined},results:comparison.results,hashes:Object.fromEntries(inputs.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]))};
fs.writeFileSync(`${dir}/verification.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,results:report.results.map(r=>({...r,shallowIncreases:r.shallowIncreases.length}))},null,2));console.log('SELECTED_ROUTES_PASS');
