import fs from 'node:fs';import {T,performer,install,measure} from './harness.mjs';
const file=process.argv[2],r=JSON.parse(fs.readFileSync(file)),score=JSON.parse(fs.readFileSync('../combined-review/candidate-v1.json'));install(score);
const zero={offset:[0,0,0],core:0,pairs:0},levels=[{t:r.lo,options:[zero]},...r.controls.map(c=>({t:c.t,options:c.options.filter(o=>o.core<=2.8&&o.pairs===0)})),{t:r.hi,options:[zero]}];
for(const l of levels)if(!l.options.length)throw Error('no safe options '+l.t);
const costs=[[0]],parents=[[-1]];
for(let i=1;i<levels.length;i++){const dt=levels[i].t-levels[i-1].t,cc=[],pp=[];for(const b of levels[i].options){let min=Infinity,from=-1;for(let j=0;j<levels[i-1].options.length;j++){const a=levels[i-1].options[j],dist=b.offset.reduce((v,x,k)=>v+(x-a.offset[k])**2,0),rate=Math.sqrt(dist)/dt,cost=costs[i-1][j]+dist/dt+Math.max(0,rate-25)**2*100+b.offset.reduce((s,x)=>s+x*x,0)*dt*.1;if(cost<min){min=cost;from=j;}}cc.push(min);pp.push(from);}costs.push(cc);parents.push(pp);}
const chosen=[];let j=0;for(let i=levels.length-1;i>=0;i--){chosen.push({t:levels[i].t,offset:levels[i].options[j].offset});j=parents[i][j];}chosen.reverse();
// Shape-preserving cubic slopes; zero endpoint tangents preserve held poses.
for(let i=0;i<chosen.length;i++){chosen[i].velocity=[0,0,0];if(i>0&&i<chosen.length-1)for(let a=0;a<3;a++){const h0=chosen[i].t-chosen[i-1].t,h1=chosen[i+1].t-chosen[i].t,d0=(chosen[i].offset[a]-chosen[i-1].offset[a])/h0,d1=(chosen[i+1].offset[a]-chosen[i].offset[a])/h1;if(d0*d1>0){const w1=2*h1+h0,w2=h1+2*h0;chosen[i].velocity[a]=(w1+w2)/(w1/d0+w2/d1);}}}
function at(t){if(t<=r.lo||t>=r.hi)return [0,0,0];let j=1;while(chosen[j].t<t)j++;const a=chosen[j-1],b=chosen[j],dt=b.t-a.t,u=(t-a.t)/dt;return a.offset.map((v,k)=>(2*u**3-3*u*u+1)*v+(u**3-2*u*u+u)*dt*a.velocity[k]+(-2*u**3+3*u*u)*b.offset[k]+(u**3-u*u)*dt*b.velocity[k]);}
const original=performer.update.bind(performer);performer.update=(...args)=>{original(...args);const t=args[0];if(t<=r.lo||t>=r.hi)return;const bone=performer.hands.find(h=>h.side===r.side).fingers[0].bones[0];bone.quaternion.premultiply(new T.Quaternion().setFromEuler(new T.Euler(...at(t),'XYZ')));bone.updateWorldMatrix(false,true);};
const ts=new Set(chosen.map(c=>c.t));for(let t=r.lo;t<r.hi;t+=.001)ts.add(t);for(const n of score.notes.filter(n=>n.hand===r.side))for(const t of [n.time,n.time+n.duration])if(t>r.lo&&t<r.hi)ts.add(t);
const failures=[];let maxCore=0,maxSpeed=0,prev=null;for(const t of [...ts].sort((a,b)=>a-b)){const m=measure(t,r.side,{targetFinger:1}),core=Math.max(0,...m.keyHits.filter(k=>k.patch===r.side+'Thumb').map(k=>k.depth)),pairs=m.crossings.reduce((s,c)=>s+c.trianglePairs,0);const tip=performer.hands.find(h=>h.side===r.side).fingers[0].tip.getWorldPosition(new T.Vector3());if(prev&&t>prev.t)maxSpeed=Math.max(maxSpeed,tip.distanceTo(prev.tip)/(t-prev.t));prev={t,tip};maxCore=Math.max(maxCore,core);if(core>3||pairs)failures.push({t,core,pairs,offset:at(t),crossings:m.crossings.map(c=>({a:c.a,b:c.b,n:c.trianglePairs}))});}
const out={prevId:r.prevId,nextId:r.nextId,lo:r.lo,hi:r.hi,side:r.side,rig:process.env.DAYBREAK_RIG_MODULE,score:r.score,chosen,samples:ts.size,maxCore,maxSpeed,failures};fs.writeFileSync(file.replace('-options8.json','-dp8.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({samples:ts.size,maxCore,maxSpeed,failures:failures.length,first:failures.slice(0,4),chosen}));
