import fs from 'node:fs';import {baseline,install,T} from './harness.mjs';import {evaluate,loss} from './metrics.mjs';
const s=JSON.parse(fs.readFileSync('candidate-seed.json')),ks=s.wristMotion.hands.find(h=>h.side==='L').knots,bk=baseline.wristMotion.hands.find(h=>h.side==='L').knots;
ks[69].position=[bk[69].position[0],bk[69].position[1],bk[69].position[2]-.028];ks[471].position[1]+=.006;Object.assign(s.notes.find(n=>n.id==='p00970'),{contactLift:.011});
const units=[{id:'p00130',k:68,neighbors:['p00129'],p:[0,.012,0,0,0,0,.259,.003,0]},{id:'p00132',k:69,neighbors:['p00130'],p:[0,0,-.028,0,0,0,.269,.002435,0]},{id:'p00455',k:236,neighbors:['p00454'],p:[0,.020,-.007,0,0,0,.269,.009212,0],departure:237},{id:'p00970',k:471,neighbors:[],p:[0,.006,0,0,0,0,.269,.011,0]}];
install(s);const records=[];
for(let pass=0;pass<2;pass++)for(const u of units){const n=s.notes.find(n=>n.id===u.id),base=baseline.notes.find(n=>n.id===u.id),times=[.001,.02,.25,.5,.75,.98,.999].map(f=>n.time+n.duration*f);for(const id of u.neighbors){const nn=s.notes.find(n=>n.id===id);times.push(nn.time+nn.duration*.9,nn.time+nn.duration-.000001);}const bounds=[[-.06,.06],[-.008,.04],[-.055,.065],[-.15,.15],[-.15,.15],[-.22,.22],[.239,.277],[.0005,.016],[-.5,.5]];let best=null,count=0;const seen=new Set();function apply(p,delay){ks[u.k].position=bk[u.k].position.map((v,i)=>v+p[i]);ks[u.k].quaternion=new T.Quaternion().setFromEuler(new T.Euler(p[3],p[4],p[5],'YXZ')).multiply(new T.Quaternion().fromArray(bk[u.k].quaternion)).toArray();Object.assign(n,{contactZ:p[6],contactLift:p[7],thumbOpposition:n.finger===1?p[8]:0});if(u.departure)ks[u.departure].moveStart=Math.min(n.time+n.duration,bk[u.departure].moveStart+delay);install(s);}
function trial(p,delay=best?.delay??u.delay??0){p=p.map((v,i)=>Math.max(bounds[i][0],Math.min(bounds[i][1],v)));const key=p.map(x=>x.toFixed(7)).join()+','+delay;if(seen.has(key))return;seen.add(key);apply(p,delay);const rows=times.map(t=>evaluate(t)),l=loss(rows),value=l.hard+l.soft*.15+p.slice(0,3).reduce((a,b)=>a+b*b,0)*10+delay*2;count++;if(!best||value<best.value)best={p,delay,value,...l,rows:rows.map(r=>({time:r.time,notes:r.active,core:r.activeCore,palm:r.palmCore,own:r.ownPairs,active:r.activePairs,idle:r.activeIdlePairs,point:r.point,contacts:r.contacts}))};}
trial(u.p,u.delay??0);if(pass===0){if(u.departure)for(const delay of [.025,.045,.065,.085])for(const y of [.010,.020,.030])trial([0,y,-.007,0,0,0,.269,.009212,0],delay);else for(const y of [0,.010,.020])for(const z of [-.025,0,.025]){const p=[...u.p];p[1]=y;p[2]=z;trial(p);}}
for(const scale of [1,.35])for(let sweep=0;sweep<2;sweep++){let changed=false;for(let axis=0;axis<9;axis++){if(n.finger!==1&&axis===8)continue;const old=best;for(const sign of [-1,1]){const p=[...old.p];p[axis]+=sign*[.010,.006,.010,.05,.05,.07,.007,.0015,.15][axis]*scale;trial(p,old.delay);}if(best!==old)changed=true;}if(u.departure){const old=best;for(const sign of [-1,1])trial(old.p,Math.max(0,Math.min(.10,old.delay+sign*.010*scale)));if(best!==old)changed=true;}if(!changed)break;}
u.p=best.p;u.delay=best.delay;apply(best.p,best.delay);records.push({id:u.id,pass,count,...best});console.log(JSON.stringify({id:u.id,pass,count,p:best.p,delay:best.delay,hard:best.hard,value:best.value}));fs.writeFileSync('candidate-refined.json',JSON.stringify(s,null,2)+'\n');fs.writeFileSync('target-fit-report.json',JSON.stringify(records,null,2)+'\n');}
