from pathlib import Path
import json,gzip,hashlib
from collections import Counter,defaultdict
root=Path(__file__).resolve().parent
load=lambda n:json.loads((root/n).read_text())
x=load('replay-summary.json');q=load('replay-queue.json');rec={r['id']:r for r in load('schedule.json')['records']}
key_counts=Counter();pair_counts=Counter();active_core=0;active_pair=0;active_own=0;strict_counts=Counter();regions=defaultdict(lambda:{'handStates':0,'events':Counter(),'firstTime':None,'lastTime':None,'worstCore':None,'worstPair':None,'supports':set()})
with gzip.open(root/'replay-regressions.jsonl.gz','rt') as f:
 for line in f:
  row=json.loads(line);active={row['side']+['Thumb','Index','Middle','Ring','Pinky'][n['finger']-1] for n in row['after']['active']};significant=[e for e in row['events'] if not e['kind'].startswith('strictExisting')]
  for e in row['events']:
   if e['kind']=='newCoreKey':key_counts[e['target']]+=1;active_core+=e['target'].split(':')[0] in active
   if e['kind']=='newNeighborPair':pair_counts[e['target']]+=1;active_pair+=any(p in active for p in e['target'].split(':'))
   if e['kind']=='newOwnPalm':active_own+=any(p in active for p in e['target'].split(':'))
   if e['kind'].startswith('strictExisting'):strict_counts[e['target']]+=1
  if significant:
   # Cluster into whole support-record identities; simultaneous records are intentionally retained.
   k=tuple(row['supportIds']);r=regions[k];r['handStates']+=1;r['firstTime']=row['time'] if r['firstTime'] is None else min(r['firstTime'],row['time']);r['lastTime']=row['time'];r['supports'].update(k)
   for e in significant:
    r['events'][e['kind']]+=1
    if 'Core' in e['kind'] and (r['worstCore'] is None or e['after']-e['before']>r['worstCore']['after']-r['worstCore']['before']):r['worstCore']={'time':row['time'],**e}
    if 'Core' not in e['kind'] and (r['worstPair'] is None or e['after']-e['before']>r['worstPair']['after']-r['worstPair']['before']):r['worstPair']={'time':row['time'],**e}
triage={'significantQueueEntries':sum(not a['kind'].startswith('strictExisting') for a in q),'strictOnlyQueueEntries':sum(a['kind'].startswith('strictExisting') for a in q),'newCoreKeys':dict(key_counts),'newNeighborPairs':dict(pair_counts),'strictExistingPairs':dict(strict_counts),'newCoreKeyStatesOnActiveDigits':active_core,'newNeighborPairStatesInvolvingActiveDigits':active_pair,'newOwnPalmStatesInvolvingActiveDigits':active_own,'significantRegions':[{**v,'events':dict(v['events']),'supports':[{'id':i,'hand':'R' if rec[i]['hi'] else 'L','finger':rec[i]['fi']+1,'previous':rec[i].get('previous'),'next':rec[i].get('next'),'begin':rec[i]['begin'],'end':rec[i]['end']} for i in sorted(v['supports'])]} for v in sorted(regions.values(),key=lambda v:v['firstTime'])]}
(root/'triage.json').write_text(json.dumps(triage,indent=2)+'\n')
c=x['counts'];p=x['parity'];v=x['coverage']
lines=['# Completed replay findings','',f"Completed {x['processed']:,} timestamps, {x['handStates']:,} affected-hand states and {x['patchStates']:,} patch states across all {v['records']} records ({v['indexRecords']} index gaps, {v['curveRecords']} curves).",'', '| Measure | Baseline | Candidate / regression |','|---|---:|---:|',f"| Core-positive patch states (>3 mm) | {c['baseCorePatchStates']:,} | {c['candidateCorePatchStates']:,} |",f"| Core-positive patch/key states (>3 mm) | {c['baseCoreKeyTypes']:,} | {c['candidateCoreKeyTypes']:,} |",f"| New >3 mm patch states | — | {c['newCorePatchStates']:,} |",f"| >0.25 mm worsened deep patch states | — | {c['worsenedCorePatchStates']:,} |",f"| New >3 mm patch/key states | — | {c['newCoreKeyTypes']:,} |",f"| >0.25 mm worsened deep patch/key states | — | {c['worsenedCoreKeyTypes']:,} |",f"| New finger-pair type states | — | {c['newNeighborPairTypes']:,} |",f"| New own-palm type states | — | {c['newOwnPalmTypes']:,} |",f"| Strict existing finger-pair increases | — | {c['strictExistingNeighborPairIncreases']:,} |",f"| Strict existing own-palm increases | — | {c['strictExistingOwnPalmIncreases']:,} |",f"| Existing pair increases >2 (finger / own-palm) | — | {c['existingNeighborIncreasesOver2']:,} / {c['existingOwnPalmIncreasesOver2']:,} |",'',f"There are {c['regressionHandStates']:,} regression hand states, including {c['strictOnlyHandStates']:,} with only strict existing-pair count increases. The detailed queue contains {x['queueEntries']} entries ({triage['significantQueueEntries']} core/new-type and {triage['strictOnlyQueueEntries']} strict existing-pair entries). Categories can overlap and must not be added as unique failures.",'',f"Active-joint parity: {p['activeFingerStates']:,} active finger states, {p['activeLocalQuaternionComponents']:,} local quaternion components and {p['activeWorldMatrixComponents']:,} world matrix components. Maximum active local/world component deltas: {p['maxActiveLocalComponentDelta']} / {p['maxActiveWorldComponentDelta']}. Wrist deltas: {p['maxWristLocalComponentDelta']} / {p['maxWristWorldComponentDelta']}.",'',f"New deep key states on active digits: {active_core}. New finger-pair states involving active digits: {active_pair}; new own-palm states involving active digits: {active_own}.",'','The helper improves the aggregate core count while introducing the regressions enumerated below. It does not pass a zero-regression combined support gate. Geometry results do not certify natural-looking hand movement.','', '## Core and new-type queue by concurrent support set','', '| Support records (hand/finger, previous → next) | Sampled failure range (s) | Hand states | Event states | Worst witness |','|---|---|---:|---|---|']
for r in triage['significantRegions']:
 support='; '.join(f"{s['id']} ({s['hand']}{s['finger']}, {s['previous'] or 'start'} → {s['next'] or 'end'})" for s in r['supports']);events=', '.join(f'{k}: {n}' for k,n in r['events'].items());w=r['worstCore'] or r['worstPair'];witness=f"{w['target']} at {w['time']:.9f}: {w['before']:.4f} → {w['after']:.4f}" if w else '—';lines.append(f"| {support} | {r['firstTime']:.9f}–{r['lastTime']:.9f} | {r['handStates']} | {events} | {witness} |")
lines+=['','The full finite `replay-queue.json` also lists every strict existing-pair group. Ranges summarize sampled states and do not imply continuous failure. Overlapping support membership is attribution context, not individual causal isolation.','','The preserved harness uses moving key core solids and owned mesh subsets; opposing-hand intersections, continuous motion/twist quality, rendering, browser playback, audio, and synchronization are outside this replay. See `README.md` for exact definitions and limitations.']
(root/'FINDINGS.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({k:v for k,v in triage.items() if k!='significantRegions'}));print('Significant support regions:',len(triage['significantRegions']))
