import fs from 'node:fs';
import crypto from 'node:crypto';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone as cloneSkeleton} from 'three/addons/utils/SkeletonUtils.js';
import {Pianist as BaselinePianist} from './baseline-runnable.mjs';
import {Pianist as DeliveryPianist} from './runtime/pianist.mjs';
import {GrandPiano} from './runtime/piano.mjs';
import {pedalPosition,scoreEnergy} from './runtime/math.mjs';

const root=new URL('.',import.meta.url),read=n=>JSON.parse(fs.readFileSync(new URL(n,root))),manifest=read('input-manifest.json'),windows=read('accepted-windows.json');
for(const[file,sha]of Object.entries(manifest.files)){const actual=crypto.createHash('sha256').update(fs.readFileSync(new URL(file,root))).digest('hex');if(actual!==sha)throw Error('Frozen input mismatch: '+file);}
const scores=[read('baseline-score.json'),read('delivery-score.json')];
if(scores[0].duration!==scores[1].duration)throw Error('Duration mismatch');
const ctx=new Proxy({},{get:(o,k)=>k in o?o[k]:(...args)=>{}});globalThis.document={createElement:()=>({width:512,height:512,getContext:()=>ctx})};globalThis.self=globalThis;
const loader=new GLTFLoader();loader.register(()=>({name:'offline-textures',loadTexture:()=>Promise.resolve(new T.Texture())}));
const bytes=fs.readFileSync(manifest.modelPath);if(crypto.createHash('sha256').update(bytes).digest('hex')!==manifest.modelSha256)throw Error('Model hash mismatch');
const gltf=await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
const rigs=[];for(const[i,Class]of[BaselinePianist,DeliveryPianist].entries()){const performer=new Class(),model=cloneSkeleton(gltf.scene),piano=new GrandPiano();await performer.load(scores[i],model);rigs.push({performer,model,piano,score:scores[i]});}
const fingerNames=['Thumb','Index','Middle','Ring','Pinky'];
function metadata(name){const side=name.startsWith('Left')?'L':name.startsWith('Right')?'R':null;const m=name.match(/(?:Left|Right)(?:Hand)?(Thumb|Index|Middle|Ring|Pinky)([123])?/);return{name,side,finger:m?fingerNames.indexOf(m[1])+1:null,joint:m?.[2]?Number(m[2]):null};}
const localNames=[...rigs[0].performer.bones.keys()].sort();
const worldNames=[];for(const hand of rigs[0].performer.hands)for(const bone of[hand.upper,hand.lower,hand.wrist,...hand.fingers.flatMap(f=>f.bones)])worldNames.push(bone.name);
const positionNames=[];for(const hand of rigs[0].performer.hands){positionNames.push({name:hand.wrist.name,type:'wrist',side:hand.side,finger:null});hand.fingers.forEach((f,i)=>positionNames.push({name:f.tip.name,type:'tip',side:hand.side,finger:i+1}));}
for(const rig of rigs){rig.local=localNames.map(n=>rig.performer.bones.get(n));rig.world=worldNames.map(n=>rig.performer.bones.get(n));rig.positions=positionNames.map(m=>m.type==='wrist'?rig.performer.hands.find(h=>h.side===m.side).wrist:rig.performer.hands.find(h=>h.side===m.side).fingers[m.finger-1].tip);if([...rig.local,...rig.world,...rig.positions].some(x=>!x))throw Error('Rig entity mismatch');}
const channels=[...localNames.map((name,index)=>({...metadata(name),id:'local:'+name,kind:'localAngular',unit:'rad/s',field:'local',index:index*4})),...worldNames.map((name,index)=>({...metadata(name),id:'world:'+name,kind:'worldAngular',unit:'rad/s',field:'world',index:index*4})),...positionNames.map((m,index)=>({...m,id:m.type+':'+m.name,kind:m.type+'Speed',unit:'m/s',field:'positions',index:index*3}))];
const makeState=()=>({local:new Float64Array(localNames.length*4),world:new Float64Array(worldNames.length*4),positions:new Float64Array(positionNames.length*3)});
const finite=rigs.map(()=>({checkedScalars:0,nonFiniteScalars:0,zeroQuaternions:0,quaternionSignFlips:0,maxRawQuaternionNormError:0,maxRawQuaternionNormErrorAt:null,examples:[]}));
const tempQ=new T.Quaternion();
function check(value,diag,time,name,field){diag.checkedScalars++;if(!Number.isFinite(value)){diag.nonFiniteScalars++;if(diag.examples.length<20)diag.examples.push({time,name,field,value:String(value)});}}
function capture(ri,time,state){const rig=rigs[ri],diag=finite[ri],pedal=pedalPosition(time,rig.score.pedals),energy=scoreEnergy(time,rig.score.sections);rig.piano.update(time,rig.score.notes,pedal);rig.performer.update(time,rig.score,rig.piano,pedal,energy);rig.model.updateMatrixWorld(true);
 const put=(q,array,index,name)=>{const norm=Math.hypot(q.x,q.y,q.z,q.w);if(!Number.isFinite(norm)||norm<1e-12){diag.zeroQuaternions++;array.fill(NaN,index,index+4);return;}const error=Math.abs(norm-1);if(error>diag.maxRawQuaternionNormError){diag.maxRawQuaternionNormError=error;diag.maxRawQuaternionNormErrorAt={time,name};}array[index]=q.x/norm;array[index+1]=q.y/norm;array[index+2]=q.z/norm;array[index+3]=q.w/norm;};
 rig.local.forEach((bone,j)=>{for(const field of['position','quaternion','scale'])for(const k of(field==='quaternion'?['x','y','z','w']:['x','y','z']))check(bone[field][k],diag,time,bone.name,field+'.'+k);for(let k=0;k<16;k++)check(bone.matrixWorld.elements[k],diag,time,bone.name,'matrixWorld.'+k);put(bone.quaternion,state.local,j*4,bone.name);});
 rig.world.forEach((bone,j)=>{bone.getWorldQuaternion(tempQ);put(tempQ,state.world,j*4,bone.name+' world');});
 rig.positions.forEach((bone,j)=>{for(let k=0;k<3;k++){const value=bone.matrixWorld.elements[12+k];check(value,diag,time,bone.name,'worldPosition.'+k);state.positions[j*3+k]=value;}});
}
const tolerance=channel=>channel.unit==='rad/s'?1e-7:1e-9;
function speed(channel,prev,next,dt,diag){const a=prev[channel.field],b=next[channel.field],j=channel.index;if(channel.field==='positions')return Math.hypot(b[j]-a[j],b[j+1]-a[j+1],b[j+2]-a[j+2])/dt;let dot=0;for(let k=0;k<4;k++)dot+=a[j+k]*b[j+k];const sign=dot<0?-1:1;if(sign<0)diag.quaternionSignFlips++;let minus=0,plus=0;for(let k=0;k<4;k++){const x=b[j+k]*sign-a[j+k],y=b[j+k]*sign+a[j+k];minus+=x*x;plus+=y*y;}return 4*Math.atan2(Math.sqrt(minus),Math.sqrt(plus))/dt;}
function accepted(channel,t0,t1){return windows.filter(w=>w.side===channel.side&&(!w.fingers||w.fingers.includes(channel.finger))&&t1>=w.lo&&t0<=w.hi).map(w=>w.id);}
const stats=channels.map(channel=>({channel,baseline:{peak:null,top:[]},delivery:{peak:null,top:[]},maxIncrease:null,maxDecrease:null,outsideMaxIncrease:null,outsideMaxAbsoluteDelta:null,outsideIncreaseCount:0,outsideChangeCount:0,outsideIncreaseRuns:[],activeRun:null}));
const record=(time0,time,frame,value)=>({frame,time0,time,value});
function retain(stat,record){if(!stat.peak||record.value>stat.peak.value)stat.peak=record;if(stat.top.length<8||record.value>stat.top[stat.top.length-1].value){stat.top.push(record);stat.top.sort((a,b)=>b.value-a.value);stat.top.length=Math.min(stat.top.length,8);}}
let previous=[makeState(),makeState()],current=[makeState(),makeState()];for(let ri=0;ri<2;ri++)capture(ri,0,previous[ri]);
const duration=scores[0].duration,steps=Math.ceil(duration*120),started=Date.now();let time0=0,invalidSpeeds=0;
console.log(JSON.stringify({phase:'sweep-start',duration,steps,localBones:localNames.length,worldBones:worldNames.length,channels:channels.length,priority:'nice 15',manifest:manifest.files['delivery-pianist.ts']}));
for(let frame=1;frame<=steps;frame++){const time=Math.min(duration,frame/120),dt=time-time0;for(let ri=0;ri<2;ri++)capture(ri,time,current[ri]);
 for(let ci=0;ci<channels.length;ci++){const channel=channels[ci],s=stats[ci],a=speed(channel,previous[0],current[0],dt,finite[0]),b=speed(channel,previous[1],current[1],dt,finite[1]);if(!Number.isFinite(a)||!Number.isFinite(b)){invalidSpeeds++;continue;}retain(s.baseline,record(time0,time,frame,a));retain(s.delivery,record(time0,time,frame,b));const delta=b-a,rec={frame,time0,time,baseline:a,delivery:b,delta,acceptedWindows:accepted(channel,time0,time)};
  if(!s.maxIncrease||delta>s.maxIncrease.delta)s.maxIncrease=rec;if(!s.maxDecrease||delta<s.maxDecrease.delta)s.maxDecrease=rec;
  const outside=rec.acceptedWindows.length===0;if(outside){if(!s.outsideMaxIncrease||delta>s.outsideMaxIncrease.delta)s.outsideMaxIncrease=rec;if(!s.outsideMaxAbsoluteDelta||Math.abs(delta)>Math.abs(s.outsideMaxAbsoluteDelta.delta))s.outsideMaxAbsoluteDelta=rec;if(Math.abs(delta)>tolerance(channel))s.outsideChangeCount++;}
  if(outside&&delta>tolerance(channel)){s.outsideIncreaseCount++;if(!s.activeRun||s.activeRun.endFrame!==frame-1){if(s.activeRun)s.outsideIncreaseRuns.push(s.activeRun);s.activeRun={startFrame:frame,endFrame:frame,time0,time,count:1,peak:rec};}else{s.activeRun.endFrame=frame;s.activeRun.time=time;s.activeRun.count++;if(delta>s.activeRun.peak.delta)s.activeRun.peak=rec;}}else if(s.activeRun){s.outsideIncreaseRuns.push(s.activeRun);s.activeRun=null;}
 }
 [previous,current]=[current,previous];time0=time;
 if(frame%1800===0||frame===steps){const progress={phase:'sweep',frame,steps,time,wallSeconds:(Date.now()-started)/1000,percent:100*frame/steps};fs.writeFileSync(new URL('progress.json',root),JSON.stringify(progress));console.log(JSON.stringify(progress));}
 if(frame%240===0)await new Promise(resolve=>setImmediate(resolve));
}
function note(n){return{id:n.id,time:n.time,end:n.time+n.duration,midi:n.midi,finger:n.finger,hand:n.hand,velocity:n.velocity};}
function context(score,channel,t0,t1){const all=channel.side?score.notes.filter(n=>n.hand===channel.side):score.notes;const finger=channel.finger?all.filter(n=>n.finger===channel.finger):all;const previous=finger.filter(n=>n.time+n.duration<=t1).at(-1),next=finger.find(n=>n.time>t1);return{handActiveAtStart:all.filter(n=>n.time<=t0&&n.time+n.duration>t0).map(note),handActiveAtEnd:all.filter(n=>n.time<=t1&&n.time+n.duration>t1).map(note),previous:previous?note(previous):null,next:next?note(next):null,eventsInSample:all.flatMap(n=>{const out=[];if(n.time>t0&&n.time<=t1)out.push({kind:'attack',...note(n)});if(n.time+n.duration>t0&&n.time+n.duration<=t1)out.push({kind:'release',...note(n)});return out;})};}
for(const s of stats){if(s.activeRun)s.outsideIncreaseRuns.push(s.activeRun);delete s.activeRun;for(const[label,ri]of[['baseline',0],['delivery',1]]){s[label].peak.context=context(scores[ri],s.channel,s[label].peak.time0,s[label].peak.time);s[label].peak.acceptedWindows=accepted(s.channel,s[label].peak.time0,s[label].peak.time);for(const peak of s[label].top)peak.context??=context(scores[ri],s.channel,peak.time0,peak.time);}
 for(const key of['maxIncrease','maxDecrease','outsideMaxIncrease','outsideMaxAbsoluteDelta'])if(s[key]){s[key].baselineContext=context(scores[0],s.channel,s[key].time0,s[key].time);s[key].deliveryContext=context(scores[1],s.channel,s[key].time0,s[key].time);}for(const run of s.outsideIncreaseRuns){run.peak.baselineContext=context(scores[0],s.channel,run.peak.time0,run.peak.time);run.peak.deliveryContext=context(scores[1],s.channel,run.peak.time0,run.peak.time);}}
const outsideIncreases=stats.filter(s=>s.outsideIncreaseCount).map(s=>({channel:s.channel,samples:s.outsideIncreaseCount,peak:s.outsideMaxIncrease,runs:s.outsideIncreaseRuns}));
const newChannelPeaksOutside=stats.filter(s=>s.delivery.peak.value>s.baseline.peak.value+tolerance(s.channel)&&!s.delivery.peak.acceptedWindows.length).map(s=>({channel:s.channel,baseline:s.baseline.peak,delivery:s.delivery.peak}));
const global={};for(const kind of[...new Set(channels.map(c=>c.kind))]){global[kind]={};for(const label of['baseline','delivery'])global[kind][label]=stats.filter(s=>s.channel.kind===kind).map(s=>({channel:s.channel,...s[label].peak})).sort((a,b)=>b.value-a.value).slice(0,12);}
const report={status:'COMPLETE_READ_ONLY',fps:120,sweepPasses:1,duration,samples:steps+1,intervals:steps,lastSampleIsExactDuration:true,wallSeconds:(Date.now()-started)/1000,definitions:{localAngular:'All named rig-bone local quaternions; each normalized, adjacent sign aligned. Angle =4*atan2(norm(q1-q0),norm(q1+q0)), divided by actual sample dt.',worldAngular:'Upper arm, forearm, wrist, and all finger-joint world quaternions, normalized and sign aligned.',tipAndWrist:'Actual world-position displacement divided by sample dt. No target-point substitute.',finite:'All named bones: position, quaternion, scale, all16 world-matrix entries; plus actual fingertip/wrist positions and quaternion validity.',extrema:'Top8 sampled values per channel; exact sample endpoints, frame, note context, and paired deltas preserved.',outside:'A movement interval is inside only when it overlaps a matching side/finger accepted window. Numerical difference counters use1e-7rad/s or1e-9m/s; raw maxima are retained regardless of that tolerance.',limitations:'120Hz sampled audit; higher-frequency between-sample extrema are not claimed. No skin/surface collision or native-film playback claim.'},inputManifest:manifest,acceptedWindows:windows,finite,invalidSpeeds,global,newChannelPeaksOutside,outsideIncreases,channels:stats};
fs.writeFileSync(new URL('motion-report.json',root),JSON.stringify(report,null,2));console.log(JSON.stringify({phase:'complete',samples:report.samples,wallSeconds:report.wallSeconds,nonFinite:finite.map(f=>f.nonFiniteScalars),invalidSpeeds,newChannelPeaksOutside:newChannelPeaksOutside.length,outsideIncreaseChannels:outsideIncreases.length}));
