import pathlib,json,hashlib
P=pathlib.Path(__file__).parent;r=json.loads((P/'motion-report.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
outsideRaw=max(abs(c['outsideMaxAbsoluteDelta']['delta'])for c in r['channels']);assert r['sweepPasses']==1 and r['samples']==27979 and r['invalidSpeeds']==0 and all(x['nonFiniteScalars']==0 and x['zeroQuaternions']==0 for x in r['finite']);assert outsideRaw==0 and not r['newChannelPeaksOutside'] and not r['outsideIncreases']
summary=dict(status='NO_NEW_OUTSIDE_WINDOW_MOTION_PEAKS',scoreSha256=r['inputManifest']['files']['delivery-score.json'],rigSha256=r['inputManifest']['files']['delivery-pianist.ts'],baselineScoreSha256=r['inputManifest']['files']['baseline-score.json'],baselineRigSha256=r['inputManifest']['files']['baseline-original.mjs'],fps=r['fps'],samples=r['samples'],intervals=r['intervals'],duration=r['duration'],sweepPasses=1,wallSeconds=r['wallSeconds'],outsideMaxRawSpeedDifference=outsideRaw,newOutsidePeakCount=0,outsideIncreaseChannels=0,finite=r['finite'],invalidSpeeds=0,globalExtrema={k:{label:v[label][0]for label in ['baseline','delivery']}for k,v in r['global'].items()},largestAcceptedLocalIncreases=[dict(channel=s['channel'],**s['maxIncrease'])for s in sorted([s for s in r['channels']if s['channel']['kind']=='localAngular'],key=lambda s:s['maxIncrease']['delta'],reverse=True)[:8]],motionReportSha256=sha(P/'motion-report.json'),auditSha256=sha(P/'audit.mjs'))
(P/'motion-summary.json').write_text(json.dumps(summary,indent=2))
lines=['# Frozen delivery motion audit','',f"One read-only paired sweep completed: **{r['samples']:,} samples at 120 Hz**, 0–{r['duration']} s, {r['wallSeconds']:.3f} s wall time. No new speed increases or per-channel peaks occur outside the accepted local windows. The maximum raw outside-window difference across all 115 speed channels is **exactly 0**.",'','All 99,493,324 checked bone/world-position scalars are finite. Zero invalid speed samples or zero-length quaternions occurred. Quaternions were normalized and adjacent signs aligned before measuring angular speed. The largest raw norm error was 3.129106e-7 in both versions.','', '| Metric | v11 maximum | Delivery maximum | Delivery interval (s) | Delivery entity |','|---|---:|---:|---|---|']
for kind,label in [('localAngular','Local angular speed (rad/s)'),('worldAngular','World angular speed (rad/s)'),('tipSpeed','Fingertip speed (m/s)'),('wristSpeed','Wrist speed (m/s)')]:
 a=r['global'][kind]['baseline'][0];b=r['global'][kind]['delivery'][0];lines.append(f"| {label} | {a['value']:.9f} | {b['value']:.9f} | {b['time0']:.12f}–{b['time']:.12f} | {b['channel']['name']} |")
lines+=['','The remaining largest speeds are unchanged baseline motion:', '', '- LH Pinky MCP angular peak: release of p00769 B2 (off 167.031339) toward p00771 C3 (attack 167.126902). Peak sample: 167.08333333333334–167.09166666666667.', '- LH Ring fingertip peak: idle after p00182 G3 (off 42.781337), during the p00184 F#4 thumb attack at 42.858164. Peak sample: 42.85–42.858333333333334.', '- LH wrist peak: released transfer after p00786 B3 (off 169.796481) toward p00788 A2 (attack 169.885523). Peak sample: 169.83333333333334–169.84166666666667.', '', 'The RH Index MCP maximum falls from 126.988123173 rad/s at 106.90833333333333 to 62.748062485 rad/s at 115.38333333333334. RH Index fingertip maximum falls from 3.553693401 to 2.676973799 m/s.','', 'Local speeds can increase within accepted corrections; those changes remain explicit in the raw report and summary JSON. The largest paired local increase is LH Index MCP at 70.975–70.98333333333333, from 4.865970898 to 45.620492397 rad/s, inside the accepted p322 window. The RH Pinky MCP release at 66.575–66.58333333333333 rises from approximately zero to 34.918168516 rad/s inside the p299 window. These do not exceed the respective full-piece channel maxima.','', 'Scope and method: local angular speed for all 67 named bones; world angular speed for 36 arm/wrist/finger bones; actual world-position speeds for ten fingertips and two wrists. All bone position/quaternion/scale/world-matrix fields were checked for finite values. No target positions replace actual tip or wrist positions. One complete 120 Hz grid was sampled, plus its exact duration endpoint; no second sweep, triangle grids, source edits, or parameter searches were performed.','', 'For unit quaternions after sign alignment, angle = 4 atan2(||q1−q0||, ||q1+q0||); speed divides by the actual sample interval. Numerical outside-change counters use 1e-7 rad/s and 1e-9 m/s, but raw outside maxima are retained and equal zero here. Accepted side/finger windows are recorded in accepted-windows.json.','', 'This is a sampled motion-regression audit. It does not establish between-sample maxima, surface clearance, anatomical quality of inherited fast motion, or continuous native-film appearance. Existing high-speed moments above remain visible for parent review.','', 'Reproduce from this directory with `nice -n 15 node audit.mjs > audit.log 2>&1`, then `python summarize.py`. Runtime modules, both scores, original baseline source, and the delivery source are copied locally. The model remains at the immutable film-snapshot path recorded with its hash in input-manifest.json. The script verifies every frozen input before sweeping.','',f"Delivery score: `{summary['scoreSha256']}`",f"Delivery rig: `{summary['rigSha256']}`",f"Raw report: `{summary['motionReportSha256']}`",f"Runnable audit: `{summary['auditSha256']}`",'']
(P/'README.md').write_text('\n'.join(lines))
files=[P/'audit.mjs',P/'prepare.py',P/'summarize.py',P/'motion-report.json',P/'motion-summary.json',P/'input-manifest.json',P/'accepted-windows.json',P/'README.md',P/'GATES.md',P/'delivery-pianist.ts',P/'delivery-score.json',P/'baseline-score.json',P/'baseline-original.mjs',P/'baseline-runnable.mjs',*sorted((P/'runtime').glob('*.mjs'))]
(P/'SHA256SUMS').write_text(''.join(sha(p)+'  '+str(p.relative_to(P))+'\n'for p in files));print(json.dumps({k:summary[k]for k in ['status','samples','outsideMaxRawSpeedDifference','motionReportSha256','auditSha256']},indent=2))
