import fs from 'fs';import {baseline,install,measure,T} from '../harness.mjs';
const qi=Number(process.argv[2]??0),tag=process.env.GRIP_TAG??String(qi),queue=JSON.parse(fs.readFileSync('../hand-runtime/long-rest-queue.json')),s=process.env.GRIP_SCORE?JSON.parse(fs.readFileSync(process.env.GRIP_SCORE)):structuredClone(baseline),explicit=process.env.GRIP_IDS?.split(','),seedNote=explicit?s.notes.find(n=>n.id===explicit[0]):null,q=seedNote?{side:seedNote.hand,time:seedNote.time+seedNote.duration*.5}:queue[qi],hand=s.wristMotion.hands.find(h=>h.side===q.side),ki=hand.knots.findLastIndex(k=>k.time<=q.time),knot=structuredClone(hand.knots[ki]),knotIndices=process.env.GRIP_KNOTS?process.env.GRIP_KNOTS.split(',').map(Number):[ki],knotsBefore=knotIndices.map(i=>structuredClone(hand.knots[i])),ns=s.notes.filter(n=>explicit?explicit.includes(n.id):n.hand===q.side&&n.time<=q.time&&n.time+n.duration>q.time).sort((a,b)=>a.midi-b.midi);if(!ns.length)throw Error('No active grip');
const assignments=process.env.GRIP_ASSIGNMENTS?JSON.parse(process.env.GRIP_ASSIGNMENTS):ns.length===2?(q.side==='L'?[[5,1],[5,2],[4,1],[4,2]]:[[1,5],[2,5],[1,4],[2,4]]):ns.length===1?[[ns[0].finger],[2],[3],[4],[5],[1]]:[ns.map(n=>n.finger)],times=process.env.GRIP_TIMES?JSON.parse(process.env.GRIP_TIMES):explicit?ns.flatMap(n=>[.001,.25,.5,.75,.999].map(f=>n.time+n.duration*f)):[q.time];let best,tried=0,seed=12345;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const ranges=[[-.09,.09],[Number(process.env.GRIP_Y_MIN??.002),.06],[-.02,.10],[-.22,.22],[-.2,.2],[-.3,.3],...ns.flatMap(()=>[[Number(process.env.GRIP_Z_MIN??.236),.273],[.001,Number(process.env.GRIP_LIFT_MAX??.009)],[-.7,.7]])];
function apply(p,assignment){knotIndices.forEach((index,j)=>{const before=knotsBefore[j];hand.knots[index].position=before.position.map((v,i)=>v+p[i]);hand.knots[index].quaternion=new T.Quaternion().setFromEuler(new T.Euler(p[3],p[4],p[5],'YXZ')).multiply(new T.Quaternion().fromArray(before.quaternion)).toArray();});ns.forEach((n,i)=>Object.assign(n,{finger:assignment[i],contactZ:p[6+i*3],contactLift:p[7+i*3],thumbOpposition:assignment[i]===1?p[8+i*3]:0}));install(s);}
function ev(p,assignment){apply(p,assignment);let key=0,contact=0,pairs=0,thumbKey=0,gap=0,criticalPairs=0;for(const t of times){const r=measure(t,q.side);key=Math.max(key,...r.keyHits.filter(h=>h.active||h.patch.endsWith('Palm')).map(h=>h.depth));thumbKey=Math.max(thumbKey,...r.keyHits.filter(h=>h.patch.endsWith('Thumb')&&h.active).map(h=>h.depth));contact=Math.max(contact,...r.contacts.map(c=>c.error*1000));gap=Math.max(gap,...r.meshContacts.map(c=>c.minGap??100));const patches=r.active.map(n=>q.side+['Thumb','Index','Middle','Ring','Pinky'][n.finger-1]);const relevant=r.crossings.filter(c=>patches.includes(c.a)||patches.includes(c.b));criticalPairs=Math.max(criticalPairs,relevant.filter(c=>c.a.endsWith('Palm')||c.b.endsWith('Palm')||(patches.includes(c.a)&&patches.includes(c.b))).reduce((a,b)=>a+b.trianglePairs,0));pairs=Math.max(pairs,relevant.reduce((a,b)=>a+b.trianglePairs,0));}
const loss=Math.max(0,key-2.8)*1000+Math.max(0,thumbKey-2.8)*1000+Math.max(0,contact-.25)*10000+Math.max(0,gap-1.8)*200+criticalPairs*1000+pairs*.001+p.slice(0,3).reduce((a,b)=>a+b*b,0)*50;const result={p:[...p],assignment:[...assignment],loss,key,thumbKey,contact,pairs,criticalPairs,gap};tried++;if(!best||loss<best.loss){best=result;fs.writeFileSync('grip-'+tag+'-best.json',JSON.stringify({qi,time:q.time,side:q.side,knot:ki,notes:ns.map(n=>n.id),tried,best},null,2));fs.writeFileSync('grip-'+tag+'-candidate.json',JSON.stringify(s));console.log(JSON.stringify(best));}return result;}
for(const assignment of assignments){let cur=ev(process.env.GRIP_INIT?JSON.parse(process.env.GRIP_INIT):[0,.027,.022,0,0,0,...ns.flatMap(()=>[.258,.004,.2])],assignment);for(let trial=0;trial<Number(process.env.GRIP_TRIALS??25);trial++){const p=ranges.map(([a,b])=>a+rand()*(b-a));const r=ev(p,assignment);if(r.loss<cur.loss)cur=r;}
for(const scale of [1,.5,.25,.1])for(let pass=0;pass<3;pass++){let changed=false;for(let axis=process.env.GRIP_CONTACT_ONLY?6:0;axis<ranges.length;axis++)for(const dir of [-1,1]){const p=[...cur.p],step=([.015,.008,.016,.075,.075,.10][axis]??[.008,.002,.20][(axis-6)%3])*scale;p[axis]=Math.max(ranges[axis][0],Math.min(ranges[axis][1],p[axis]+dir*step));const r=ev(p,assignment);if(r.loss<cur.loss){cur=r;changed=true;}}if(!changed)break;}}
fs.writeFileSync('grip-'+tag+'-complete.json',JSON.stringify({qi,time:q.time,side:q.side,knot:ki,notes:ns.map(n=>n.id),tried,best},null,2));
