import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const read=f=>JSON.parse(fs.readFileSync(f)),base=read('baseline-score.json'),score=read('diagnostic-candidate.json'),delta=read('diagnostic-delta.json'),allowed=new Set(['p00511','p00513','p00514','p00516','p00518','p00899','p00903','p00905','p00907','p00909']);
assert.equal(crypto.createHash('sha256').update(fs.readFileSync('baseline-score.json')).digest('hex'),'7cc3dbdd44befd4d22793a8ac266a8414480a8486e79167b1552514087f7a1c1');
for(let i=0;i<base.notes.length;i++){const a=base.notes[i],b=score.notes[i];assert.equal(a.id,b.id);for(const k of ['id','time','duration','midi','velocity','hand','role','bar','beat','writtenDuration'])assert.deepEqual(a[k],b[k],a.id+'.'+k);if(!allowed.has(a.id))assert.deepEqual(a,b,'outside note '+a.id);for(const k of new Set([...Object.keys(a),...Object.keys(b)]))if(a[k]!==b[k])assert(['contactLift','contactZ','thumbOpposition','finger'].includes(k));}
for(const hand of base.wristMotion.hands){const other=score.wristMotion.hands.find(h=>h.side===hand.side);for(let i=0;i<hand.knots.length;i++){const changed=hand.side==='L'&&[262,263,264,265,442,443,444,445,446].includes(i);if(!changed)assert.deepEqual(hand.knots[i],other.knots[i],'outside knot '+hand.side+i);if(hand.side==='L'&&i===446){assert.deepEqual(hand.knots[i].position,other.knots[i].position);assert.deepEqual(hand.knots[i].quaternion,other.knots[i].quaternion);assert.equal(hand.knots[i].time,other.knots[i].time);}}}
for(const k of Object.keys(base))if(!['notes','wristMotion'].includes(k))assert.deepEqual(base[k],score[k],k);
assert.deepEqual(read('second-held-candidate.json'),read('second-held-reapplied.json'));
for(const r of read('held-summary.json').filter(r=>r.scope==='p905')){assert.equal(r.badSamples,0);assert(r.maxKeyMm<=3);assert.equal(r.maxCrossingPairs,0);assert(r.minPadMm>=-2.5&&r.maxPadMm<=2.5);assert(r.maxPointMm<.001);}
for(const e of read('render-manifest.json')){assert(e.inspected);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(e.path)).digest('hex'),e.sha256);}
for(const row of read('diagnostic-candidate-garment.json').rows)for(const r of row.surfaces){assert.equal(r.maxDepthMm,0);assert.equal(r.forearmCrossings,0);}
console.log('PASS — frozen inputs, musical/outside guards, second held-only geometry, garment samples, and 12 inspected render hashes. Full passage acceptance remains rejected.');
