import fs from 'node:fs';import {T,baseline,install,isBlack} from './harness.mjs';import {evaluate} from './metric.mjs';
const score=JSON.parse(fs.readFileSync('candidate-natural.json')),knots=score.wristMotion.hands.find(h=>h.side==='L').knots,bk=baseline.wristMotion.hands.find(h=>h.side==='L').knots,prior=JSON.parse(fs.readFileSync('natural-fit-report.json')).params,deg=Math.PI/180;
knots[263].moveStart+=.022;knots[264].moveStart+=.015;
score.notes.find(n=>n.id==='p00513').finger=2;
const units=[['p00513',262],['p00514',263],['p00516',264],['p00518',265]],ps=new Map(units.map(([id])=>[id,prior[id]??[-.025,.012,.010,-20*deg,.269,.002865]]));
function set(id,k,p){knots[k].position=bk[k].position.map((v,i)=>v+p[i]);knots[k].quaternion=new T.Quaternion().fromArray(bk[k].quaternion).premultiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),p[3])).toArray();Object.assign(score.notes.find(n=>n.id===id),{contactZ:p[4],contactLift:p[5]});}for(const [id,k]of units)set(id,k,ps.get(id));install(score);
const rounds=[];
for(let pass=0;pass<3;pass++)for(const [id,k]of units){const n=score.notes.find(n=>n.id===id),times=[.001,.02,.25,.5,.8,.98,.999].map(f=>n.time+n.duration*f),prev=score.notes.filter(n=>n.hand==='L'&&n.time<n.time);const last=units.find(u=>u[1]===k-1);if(last){const pn=score.notes.find(n=>n.id===last[0]);times.push(pn.time+pn.duration*.98,pn.time+pn.duration-.000001);}const black=isBlack(n.midi),bounds=[[-.09,.035],[-.005,.05],[-.05,.080],[-50*deg,-18*deg],[black?.166:.239,black?.211:.282],[.0005,.016]],seen=new Set();let best=null,trials=0;
 const trial=p=>{p=p.map((v,i)=>Math.max(bounds[i][0],Math.min(bounds[i][1],v)));const key=p.map(v=>v.toFixed(7)).join();if(seen.has(key))return;seen.add(key);set(id,k,p);install(score);const rs=times.map(time=>{const r=evaluate(time);return{time,key:r.keyCore,pairs:r.crossingPairs,gaps:r.contacts.map(c=>c.padGap),point:r.pointContactMm,lateral:r.lateralPalmFrameDegrees};}),geometry=rs.reduce((s,r)=>s+Math.max(0,r.key-2.8)*100+r.pairs*4+Math.max(0,r.point-.15)*350+r.gaps.reduce((a,g)=>a+(g==null?1500:Math.max(0,Math.abs(g)-2.3)*120),0),0),loss=geometry+rs.reduce((s,r)=>s+Math.max(0,Math.abs(r.lateral)-16),0);trials++;if(!best||loss<best.loss)best={p,loss,geometry,results:rs};};trial(ps.get(id));if(pass===0&&['p00513','p00516'].includes(id)){for(const dz of [.010,.025,.04,.060])for(const dy of [.008,.020,.035])for(const depth of [.239,.269]){const p=[...ps.get(id)];p[2]=dz;p[1]=dy;p[4]=depth;trial(p);}}
 for(const scale of [1,.4])for(let sweep=0;sweep<2;sweep++){let improve=false;for(let axis=0;axis<6;axis++){const old=best;for(const sign of [-1,1]){const p=[...old.p];p[axis]+=sign*[.006,.004,.004,3*deg,.006,.0015][axis]*scale;trial(p);}if(best!==old)improve=true;}if(!improve)break;}
 ps.set(id,best.p);set(id,k,best.p);install(score);rounds.push({pass,id,trials,...best});console.log(JSON.stringify({pass,id,trials,...best}));fs.writeFileSync('candidate-first.json',JSON.stringify(score,null,2)+'\n');fs.writeFileSync('first-fit-report.json',JSON.stringify({params:Object.fromEntries(ps),rounds},null,2)+'\n');}
