import fs from 'node:fs';import {T,baseline,install,performer,update} from './harness.mjs';import {evaluate} from './metric.mjs';
const baseScore=JSON.parse(fs.readFileSync('target-score.json')),results=[],deg=Math.PI/180,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
for(const [time,id,yaws]of [[105.7149985,'p00514',[-25,-30,-35]],[187.4408685,'p00905',[-35,-40,-45,-50]]]){
 const score=structuredClone(baseScore),note=score.notes.find(n=>n.id===id),original=structuredClone(note);install(score);globalThis.daybreakYawPose=[0,0,0,0];update(time);const hand=performer.hands.find(h=>h.side==='L'),finger=hand.fingers[note.finger-1],mcp=finger.bones[0].getWorldPosition(new T.Vector3()),wrist=hand.wrist.getWorldPosition(new T.Vector3()),offset=mcp.clone().sub(wrist),base=evaluate(time);let best=null,clear=null,tried=0;const rows=[],seen=new Set();
 const trial=p=>{p=[clamp(p[0],-.025,.025),clamp(p[1],-.015,.015),clamp(p[2],-.03,.02),clamp(p[3],-55*deg,-20*deg),clamp(p[4],.166,.211),clamp(p[5],.0005,.016)];const key=p.map(n=>n.toFixed(7)).join(',');if(seen.has(key))return;seen.add(key);globalThis.daybreakYawPose=p;note.contactZ=p[4];note.contactLift=p[5];const r=evaluate(time),gaps=r.contacts.map(c=>c.padGap),missing=gaps.filter(x=>x===null).length,minGap=Math.min(...gaps.filter(x=>x!==null)),maxGap=Math.max(...gaps.filter(x=>x!==null)),geometry=Math.max(0,r.keyCore-2.8)*100+r.crossingPairs*4+Math.max(0,-2.3-minGap)*100+Math.max(0,maxGap-2.3)*100+missing*1000+Math.max(0,r.pointContactMm-.2)*250,lateral=Math.abs(r.lateralPalmFrameDegrees),loss=geometry+Math.max(0,lateral-12)*4+Math.hypot(p[0],p[1],p[2])*40,result={p:[...p],loss,geometry,r};rows.push(result);tried++;if(!best||loss<best.loss)best=result;if(geometry<1e-7&&lateral<=15&&(!clear||lateral<Math.abs(clear.r.lateralPalmFrameDegrees)))clear=result;return result;};
 for(const yaw of yaws){const angle=yaw*deg,rotated=offset.clone().applyAxisAngle(new T.Vector3(0,1,0),angle),anchor=offset.clone().sub(rotated);for(const factor of [.5,1])for(const dy of [-.008,0,.008])for(const depth of [.196,.211])trial([anchor.x*factor,dy,anchor.z*factor,angle,depth,original.contactLift]);}
 for(const scale of [1,.5,.25])for(let pass=0;pass<2;pass++){const origin=[...best.p];for(let axis=0;axis<6;axis++)for(const sign of [-1,1]){const p=[...origin];p[axis]+=sign*[.006,.004,.006,4*deg,.006,.0015][axis]*scale;trial(p);}}
 const chosen=clear??best;globalThis.daybreakYawPose=chosen.p;note.contactZ=chosen.p[4];note.contactLift=chosen.p[5];const row={time,id,base,tried,clear:!!clear,chosen,rows};results.push(row);fs.writeFileSync(id+'-coupled-score.json',JSON.stringify(score));fs.writeFileSync(id+'-coupled-report.json',JSON.stringify(row,null,2));console.log(JSON.stringify({time,id,tried,clear:!!clear,p:chosen.p,lateral:chosen.r.lateralPalmFrameDegrees,angle:chosen.r.threeDimensionalDegrees,key:chosen.r.keyCore,pairs:chosen.r.crossingPairs,pad:chosen.r.contacts.map(c=>c.padGap),point:chosen.r.pointContactMm}));
}
fs.writeFileSync('coupled-fit-report.json',JSON.stringify(results,null,2));
