import fs from'node:fs';import crypto from'node:crypto';import{performer,model,piano,update,T}from'./harness.mjs';import{evaluate}from'./metrics.mjs';
const times=new Set();const add=t=>times.add(Math.round(t*1e9)/1e9);
for(let i=0;i<=300;i++)add(64.15+i/60);for(let i=0;i<=650;i++)add(65.9+i*.002);for(let i=0;i<=175;i++)add(64.15+i*.002);
for(const file of ['../integrated-review/score-v11.json','candidate-score.json']){const s=JSON.parse(fs.readFileSync(new URL(file,import.meta.url)));for(const n of s.notes.filter(n=>n.time<69.151&&n.time+n.duration>64.15))for(const e of[n.time,n.time+n.duration])for(const d of[-1e-6,0,1e-6])if(e+d>=64.15&&e+d<=69.15)add(e+d);}
for(const e of[65.9,66.03,66.18,66.28,66.54,66.568093,66.668093,67.016236,68.32,68.37,68.41,68.448307])for(const d of[-1e-6,0,1e-6])add(e+d);
const digest=()=>{const data=[];model.traverse(b=>{if(b.isBone)data.push(b.name,...b.position.toArray(),...b.quaternion.toArray(),...b.matrixWorld.elements);});for(const k of piano.keys.values())data.push(k.midi,...k.mesh.matrixWorld.elements);return crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex');};
const rows=[],poses=[];for(const t of [...times].sort((a,b)=>a-b)){rows.push(evaluate(t,'R'));poses.push([t,digest()]);}
const outside=[0,63.5,64.15,64.184353,67.016237,67.200001,67.5,68.32,68.37,68.41,68.448307,69.2,150,230].map(time=>{update(time);return{time,sha:digest()};});
const peaks={};const record=(k,m)=>{if(!peaks[k]||m.value>peaks[k].value)peaks[k]=m;};for(const[start,count]of[[64.15,700],[65.9,2600]]){let prev,prevV;for(let i=0;i<=count;i++){const time=start+i*.0005;update(time);const h=performer.hands[1],qs=h.fingers.map(f=>f.bones.map(b=>b.quaternion.clone())),w=h.wrist.getWorldPosition(new T.Vector3());if(prev){for(let fi=0;fi<5;fi++)for(let j=0;j<3;j++)record('joint'+fi,{time,fi,j,value:qs[fi][j].angleTo(prev.qs[fi][j])*2000});const v=w.clone().sub(prev.w).multiplyScalar(2000);record('wrist',{time,value:v.length()});if(prevV)record('wristAcceleration',{time,value:v.distanceTo(prevV)*2000});prevV=v;}prev={qs,w};}}
const summary={states:rows.length,activeCore:Math.max(...rows.map(r=>r.activeCore)),allCore:Math.max(...rows.map(r=>r.allCore)),palmCore:Math.max(...rows.map(r=>r.palmCore)),pairs:rows.reduce((s,r)=>s+r.allPairs,0),maxPairs:Math.max(...rows.map(r=>r.allPairs)),gap:Math.max(...rows.flatMap(r=>r.contacts.map(c=>Math.abs(c.gap??999)))),point:Math.max(...rows.map(r=>r.point)),peaks,outside};fs.writeFileSync(process.argv[2],JSON.stringify({summary,rows,poses}));console.log(JSON.stringify({...summary,outside:undefined}));
