import fs from'node:fs';import crypto from'node:crypto';import{performer,model,piano,update,T,baseline}from'./harness.mjs';import{evaluate}from'./metrics.mjs';
const times=new Set(Array.from({length:501},(_,i)=>106.6+i*.002));for(const n of baseline.notes.filter(n=>n.time<107.65&&n.time+n.duration>106.6))for(const e of[n.time,n.time+n.duration])for(const d of[-1e-6,0,1e-6])if(e+d>=106.6&&e+d<=107.6)times.add(e+d);for(const e of[106.65,106.78,106.81,106.895774,106.923274,107.18,107.241383,107.269683,107.35,107.55])for(const d of[-1e-6,0,1e-6])times.add(e+d);
const rows=[...times].sort((a,b)=>a-b).map(t=>evaluate(t,'R'));
const outside=[0,104.7,106.2,106.599999,106.649999,107.550001,107.600001,108,150,230].map(time=>{update(time);const data=[];model.traverse(b=>{if(b.isBone)data.push(b.name,...b.position.toArray(),...b.quaternion.toArray(),...b.matrixWorld.elements);});for(const k of piano.keys.values())data.push(k.midi,...k.mesh.matrixWorld.elements);return{time,sha:crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex')};});
let prev=null,previousSpeed=null;const moves=[];for(let i=0;i<=2000;i++){const time=106.6+i*.0005;update(time);const h=performer.hands[1],qs=h.fingers.map(f=>f.bones.map(b=>b.quaternion.clone())),w=h.wrist.getWorldPosition(new T.Vector3()),points=h.fingers.map(f=>f.tip.getWorldPosition(new T.Vector3()));if(prev){for(let fi=0;fi<5;fi++)for(let j=0;j<3;j++)moves.push({time,kind:'joint',fi,j,value:qs[fi][j].angleTo(prev.qs[fi][j])/.0005});const velocity=w.clone().sub(prev.w).multiplyScalar(2000);moves.push({time,kind:'wrist',value:velocity.length()});if(previousSpeed)moves.push({time,kind:'wristAcceleration',value:velocity.distanceTo(previousSpeed)*2000});previousSpeed=velocity;for(let fi=0;fi<5;fi++)moves.push({time,kind:'tip',fi,value:points[fi].distanceTo(prev.points[fi])/.0005});}prev={qs,w,points};}
const peaks={};for(const m of moves){const name=m.kind+(m.fi!==undefined?m.fi:'');if(!peaks[name]||m.value>peaks[name].value)peaks[name]=m;}
const families=[...new Set(rows.flatMap(r=>r.crossings.map(c=>c.a+'/'+c.b)))];
const summary={surfaceSamples:rows.length,activeCore:Math.max(...rows.map(r=>r.activeCore)),palmCore:Math.max(...rows.map(r=>r.palmCore)),allCore:Math.max(...rows.map(r=>r.allCore)),point:Math.max(...rows.map(r=>r.point)),gap:Math.max(...rows.flatMap(r=>r.contacts.map(c=>Math.abs(c.gap??999)))),pairsSum:rows.reduce((n,r)=>n+r.allPairs,0),maxPairs:Math.max(...rows.map(r=>r.allPairs)),families,peaks,outside,violations:rows.filter(r=>r.activeCore>2.8||r.palmCore>2.8||r.point>.15||r.contacts.some(c=>c.gap===null||Math.abs(c.gap)>2.3)).map(r=>({t:r.time,activeCore:r.activeCore,palmCore:r.palmCore,point:r.point,contacts:r.contacts}))};
fs.writeFileSync(process.argv[2],JSON.stringify({summary,rows}));console.log(JSON.stringify({...summary,outside:undefined,peaks,violations:summary.violations.slice(0,10)},null,2));
