import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const read=f=>JSON.parse(fs.readFileSync(f)),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),manifest=read('manifest.json'),base=fs.readFileSync('pianist-baseline.ts','utf8');
assert.equal(sha('baseline-score.json'),'335e91845dfb5a6126e7b83d1818ac841f6852694f24348b24e0f182c3b76e60');assert.equal(sha('pianist-baseline.ts'),manifest.baselineSourceSha256);assert.equal(sha('compiled/wrist-motion.mjs'),manifest.wristArcModuleSha256);assert.equal(sha('pianist.glb'),manifest.modelSha256);assert.equal(manifest.variants.length,9);
const start=base.indexOf(' if(!n&&fi>0){'),end=base.indexOf('\n\n for(let j=0;j<3;j++){',start);for(const v of manifest.variants){assert.equal(sha(v.name+'.ts'),v.sourceSha256);const source=fs.readFileSync(v.name+'.ts','utf8');assert.equal(source.slice(0,start),base.slice(0,start));assert.equal(source.slice(source.indexOf('\n\n for(let j=0;j<3;j++){',start)),base.slice(end));}
for(const r of read('seven-comparison.json')){assert.equal(r.heldQuaternionMaxComponentDelta,0);assert.equal(r.heldPointMaxComponentDelta,0);assert.equal(r.rows.length,46);}const screen=read('screen-report.json');assert.equal(screen.scheduleSamples,1070);assert.equal(screen.neutralSamples,7);assert.equal(screen.activeQuatDelta,0);assert.equal(screen.activeTipDelta,0);assert.equal(screen.heldJoints,7539);assert.equal(screen.regressions.length,959);
for(const v of read('motion-screen-report.json')){assert.equal(v.boundarySamples,2121);assert.equal(v.boundaryExceedances.length,0);assert(v.seeking.every(x=>x.maxQComponent===0&&x.maxTipComponent===0));}
for(const s of read('qualification-subset.json')){assert(s.samples>=20&&s.duration>=.08);assert(s.maxCoreMm<=3);assert.equal(s.maxPairs,0);assert(s.maxPointMm<=.2);}
const renders=read('render-manifest.json');assert.equal(renders.length,14);for(const r of renders){assert(r.inspected);assert.equal(sha(r.path),r.sha256);const report=read(r.report);assert.equal(report.sourceSha256['public/assets/score.json'],manifest.scoreSha256);assert.equal(report.sourceSha256['app/performance/wrist-motion.ts'],sha('wrist-motion-source.ts'));}
console.log('PASS: nine variants, source/held parity, best-only1070 screen, 2121 boundaries, seven observed clear segments,14 inspected actual render hashes. Global candidate remains rejected.');
