import fs from 'node:fs';import path from 'node:path';
const manifest=JSON.parse(fs.readFileSync('manifest.json')),result=[];const qa=(T,a,b)=>new T.Quaternion().fromArray(a).normalize().angleTo(new T.Quaternion().fromArray(b).normalize());
for(const variant of ['pianist-baseline','neutral-f72-d0']){process.env.DAYBREAK_RIG_MODULE=path.resolve(variant+'.mjs');const A=await import('./harness.mjs?motion-'+variant),{T,performer,baseline,update}=A;
 function pose(time){update(time);return performer.hands.flatMap(h=>h.fingers.map((f,fi)=>({side:h.side,finger:fi+1,q:f.bones.map(b=>b.quaternion.toArray()),tip:f.tip.getWorldPosition(new T.Vector3()).toArray()})));}
 const boundaryTimes=[...new Set(baseline.notes.flatMap(n=>[n.time,n.time+n.duration]))].sort((a,b)=>a-b),boundaries=[];for(const time of boundaryTimes){const a=pose(time-1e-6),b=pose(time+1e-6);for(let i=0;i<10;i++){const angle=Math.max(...a[i].q.map((q,j)=>qa(T,q,b[i].q[j]))),tip=new T.Vector3().fromArray(a[i].tip).distanceTo(new T.Vector3().fromArray(b[i].tip))*1000;if(angle>.001||tip>.01)boundaries.push({time,side:a[i].side,finger:a[i].finger,angleRad:angle,tipStepMm:tip});}}
 const windows=[];for(const centre of manifest.neutralTimes){const lo=centre-.35,hi=centre+.35;let prev=null;const rates=[];let maxJoint=0,maxTip=0,worst=null;for(let time=lo;time<=hi;time+=1/240){const r=pose(time);if(prev)for(let i=0;i<10;i++){const joint=Math.max(...r[i].q.map((q,j)=>qa(T,q,prev[i].q[j])))*240,tip=new T.Vector3().fromArray(r[i].tip).distanceTo(new T.Vector3().fromArray(prev[i].tip))*240;if(joint>maxJoint){maxJoint=joint;worst={time,side:r[i].side,finger:r[i].finger};}maxTip=Math.max(maxTip,tip);if(joint>100)rates.push({time,side:r[i].side,finger:r[i].finger,jointRadSec:joint,tipMsec:tip});}prev=r;}windows.push({centre,lo,hi,samples:169,maxJointRadSec:maxJoint,maxTipMsec:maxTip,worst,highRates:rates});}
 const seeking=[];for(const t of manifest.neutralTimes){const a=pose(t);pose(224.5-t/10);const b=pose(t);seeking.push({time:t,maxQComponent:Math.max(...a.flatMap((r,i)=>r.q.flatMap((q,j)=>q.map((v,k)=>Math.abs(v-b[i].q[j][k]))))),maxTipComponent:Math.max(...a.flatMap((r,i)=>r.tip.map((v,k)=>Math.abs(v-b[i].tip[k]))))});}
 result.push({variant,boundarySamples:boundaryTimes.length,boundaryThresholds:{jointRad:.001,tipStepMm:.01},boundaryExceedances:boundaries,windows,seeking});console.log(variant,boundaryTimes.length,boundaries.length,windows.map(w=>w.maxJointRadSec));}
fs.writeFileSync('motion-screen-report.json',JSON.stringify(result,null,2)+'\n');
