import {T,body,piano,performer,measure,isBlack,baseline} from './harness.mjs';
const names=['Thumb','Index','Middle','Ring','Pinky'],a=body.geometry.attributes,pads=[];
for(let finger=0;finger<5;finger++){const ids=[];for(let i=0;i<a.position.count;i++)for(let j=0;j<4;j++)if(body.skeleton.bones[a.skinIndex.getComponent(i,j)].name==='RightHand'+names[finger]+'3'&&a.skinWeight.getComponent(i,j)>.65){ids.push(i);break;}pads.push(ids);}
export function sample(time,{exact=true}={}){const r=measure(time,'R',{exact,opposing:true}),contacts=[];
 for(const note of r.active){const key=piano.keys.get(note.midi),box=key.mesh.geometry.boundingBox,inverse=key.mesh.matrixWorld.clone().invert(),bevel=isBlack(note.midi)?.002:.0014;let gap=Infinity,count=0,vertex=null,point=null;
  for(const id of pads[note.finger-1]){const world=body.getVertexPosition(id,new T.Vector3()).applyMatrix4(body.matrixWorld),p=world.clone().applyMatrix4(inverse);if(p.x<box.min.x+bevel||p.x>box.max.x-bevel||p.z<box.min.z+bevel||p.z>box.max.z-bevel)continue;count++;const value=(p.y-box.max.y)*1000;if(value<gap){gap=value;vertex=id;point=world.toArray();}}
  contacts.push({...note,padGap:Number.isFinite(gap)?gap:null,count,vertex,point,surfaceGap:r.meshContacts.find(c=>c.id===note.id)?.minGap??null});
 }
 const f=performer.hands.find(h=>h.side==='R').fingers,turns=f.map((f,fi)=>({finger:fi+1,localRotation:f.bones.map((b,j)=>b.quaternion.clone().normalize().angleTo(f.rest[j].clone().normalize()))}));
 return{time,active:r.active,contacts,keyCore:Math.max(0,...r.keyHits.map(h=>h.depth)),keyHits:r.keyHits,crossingPairs:r.crossings.reduce((n,c)=>n+c.trianglePairs,0),crossings:r.crossings,pointContactMm:Math.max(0,...r.contacts.map(c=>c.error*1000)),wrist:r.wrist,chains:r.chains,turns};
}
export function summarize(rows){const contacts=rows.flatMap(r=>r.contacts),q={samples:rows.length,keyCore:Math.max(0,...rows.map(r=>r.keyCore)),minimumPadGap:Math.min(...contacts.map(c=>c.padGap??Infinity)),maximumPadGap:Math.max(...contacts.map(c=>c.padGap??-Infinity)),missingPad:contacts.filter(c=>c.padGap===null).length,crossingPairs:Math.max(0,...rows.map(r=>r.crossingPairs)),pointContactMm:Math.max(0,...rows.map(r=>r.pointContactMm)),thumbFirstBoneRotation:Math.max(0,...rows.map(r=>r.turns[0].localRotation[0]))};q.bad=q.keyCore>3||q.minimumPadGap< -2.5||q.maximumPadGap>2.5||q.missingPad>0||q.crossingPairs>0||q.pointContactMm>.25;return q;}
export function times(score,start,end,hz=120){const result=[];for(let t=start;t<=end;t+=1/hz)result.push(t);result.push(end);const knots=score.wristMotion.hands.find(h=>h.side==='R').knots;const events=knots.flatMap(k=>[k.time,k.moveStart,k.moveEnd]).filter(Number.isFinite).concat(score.notes.flatMap(n=>[n.time,n.time+n.duration]));for(const e of events)for(const eps of [-.0001,0,.0001])if(e+eps>=start&&e+eps<=end)result.push(e+eps);return[...new Set(result.map(t=>+t.toFixed(8)))].sort((a,b)=>a-b);}
