import fs from 'node:fs';import assert from 'node:assert/strict';import {baseline,install,T} from './harness.mjs';import {sample,summarize,times} from './metric.mjs';
const own=JSON.parse(fs.readFileSync('reservation.json')),candidate=JSON.parse(fs.readFileSync('diagnostic-score.json')),reports={},fingerNames=['Thumb','Index','Middle','Ring','Pinky'];
for(const[label,score]of [['baseline',baseline],['diagnostic',candidate]]){install(score);const grid=times(score,own.incomingStart,own.contextEnd,240),rows=grid.map(t=>sample(t)),motion={wristMps:0,fingerJointMps:0,wristAt:0,fingerAt:0};for(let i=1;i<rows.length;i++){const a=rows[i-1],b=rows[i],dt=b.time-a.time;if(dt<1e-7)continue;const speed=new T.Vector3().fromArray(a.wrist).distanceTo(new T.Vector3().fromArray(b.wrist))/dt;if(speed>motion.wristMps){motion.wristMps=speed;motion.wristAt=b.time;}for(let f=0;f<5;f++)for(let j=0;j<4;j++){const speed=new T.Vector3().fromArray(a.chains[f].points[j]).distanceTo(new T.Vector3().fromArray(b.chains[f].points[j]))/dt;if(speed>motion.fingerJointMps){motion.fingerJointMps=speed;motion.fingerAt=b.time;}}}
 const perNote=own.noteIds.map(id=>{const rs=rows.filter(r=>r.active.some(n=>n.id===id)),note=score.notes.find(n=>n.id===id),name='R'+fingerNames[note.finger-1];return{id,summary:summarize(rs),activeKeyCore:Math.max(0,...rs.flatMap(r=>r.keyHits.filter(h=>h.patch===name).map(h=>h.depth))),activeCrossingPairs:Math.max(0,...rs.map(r=>r.crossings.filter(c=>c.a===name||c.b===name).reduce((s,c)=>s+c.trianglePairs,0)))};});
 reports[label]={summary:summarize(rows),primarySummary:summarize(rows.filter(r=>r.time<=own.heldEnd)),motion,perNote,rows};console.log(label,JSON.stringify({summary:reports[label].summary,motion,perNote}));
}
const delta={knots:[],notes:[]};for(const i of own.knotIndices){const before=baseline.wristMotion.hands[1].knots[i],after=candidate.wristMotion.hands[1].knots[i];if(JSON.stringify(before)!==JSON.stringify(after))delta.knots.push({side:'R',index:i,before,after});}for(let i=0;i<baseline.notes.length;i++){const a=baseline.notes[i],b=candidate.notes[i];if(JSON.stringify(a)!==JSON.stringify(b))delta.notes.push({id:a.id,before:a,after:b});}
const a=structuredClone(baseline),b=structuredClone(candidate);for(const r of delta.notes){assert.ok(own.noteIds.includes(r.id));for(const k of ['time','duration','midi','velocity','hand','finger'])assert.deepEqual(r.before[k],r.after[k]);b.notes[b.notes.findIndex(n=>n.id===r.id)]=a.notes.find(n=>n.id===r.id);}for(const r of delta.knots)b.wristMotion.hands[1].knots[r.index]=a.wristMotion.hands[1].knots[r.index];assert.deepEqual(a,b);
fs.writeFileSync('diagnostic-delta.json',JSON.stringify(delta,null,2));fs.writeFileSync('validation-report.json',JSON.stringify(reports,null,2));
const bad=reports.diagnostic.rows.filter(r=>r.keyCore>3||r.crossingPairs||r.contacts.some(c=>c.padGap===null||Math.abs(c.padGap)>2.5));const spans=[];for(const r of bad){let span=spans.at(-1);if(!span||r.time-span.end>.01){span={start:r.time,end:r.time,maxKeyCore:0,maxPairs:0,patches:new Set(),worst:null};spans.push(span);}span.end=r.time;if(r.keyCore>span.maxKeyCore){span.maxKeyCore=r.keyCore;span.worst=r;}span.maxPairs=Math.max(span.maxPairs,r.crossingPairs);for(const h of r.keyHits)if(h.depth>3)span.patches.add(h.patch+'/key');for(const c of r.crossings)span.patches.add(c.a+'/'+c.b);}
fs.writeFileSync('residual-intervals.json',JSON.stringify(spans.map(s=>({...s,patches:[...s.patches],worst:s.worst?{time:s.worst.time,active:s.worst.active,keyHits:s.worst.keyHits,crossings:s.worst.crossings}:null})),null,2));console.log('Verified authored events/fingering unchanged; diagnostic candidate remains rejected due actual whole-hand residuals.');
