import fs from 'node:fs';import {T,score,performer,piano,model,wp,pose,fingers} from './runtime.mjs';import {keyX,isBlack,keySurfaceY} from './compiled/piano.mjs';
let body;model.traverse(o=>{if(o.isSkinnedMesh&&o.name==='Human')body=o;});const positions=body.geometry.attributes.position,si=body.geometry.attributes.skinIndex,sw=body.geometry.attributes.skinWeight;
// Locate pad vertices in bind coordinates using the bone inverse, independent of current pose.
const pads={};for(const side of ['L','R'])for(let fi=0;fi<5;fi++){const name=(side==='L'?'Left':'Right')+'Hand'+['Thumb','Index','Middle','Ring','Pinky'][fi]+'3',bi=body.skeleton.bones.findIndex(b=>b.name===name),inv=body.skeleton.boneInverses[bi],list=[];for(let i=0;i<si.count;i++){let w=0;for(let j=0;j<4;j++)if(si.getComponent(i,j)===bi)w+=sw.getComponent(i,j);if(w<.35)continue;const v=new T.Vector3().fromBufferAttribute(positions,i).applyMatrix4(body.bindMatrix).applyMatrix4(inv);list.push({i,y:v.y});}const max=Math.max(...list.map(x=>x.y));pads[side+(fi+1)]=list.filter(x=>x.y>max-.011).map(x=>x.i);}
function rebuild(){for(const h of performer.hands)h.fingerNotes=Array.from({length:5},(_,i)=>h.notes.filter(n=>n.finger===i+1));}
function sample(n,t){pose(t);body.skeleton.update();const h=performer.hands[n.hand==='L'?0:1],f=h.fingers[n.finger-1],points=[...f.bones,f.tip].map(wp),dir=points[1].clone().sub(points[0]).normalize().applyQuaternion(h.wrist.getWorldQuaternion(new T.Quaternion()).invert());let gap=Infinity,count=0;const x=keyX(n.midi),black=isBlack(n.midi),half=black?.00725:.01135,v=new T.Vector3();for(const i of pads[n.hand+n.finger]){body.getVertexPosition(i,v).applyMatrix4(body.matrixWorld);if(Math.abs(v.x-x)>half||v.z<(black?.133:.230)||v.z>(black?.221:.279))continue;gap=Math.min(gap,v.y-keySurfaceY(n.midi,v.z));count++;}const error=performer.contacts.find(c=>c.hand===n.hand&&c.finger===n.finger&&c.midi===n.midi)?.error??1;return {gap,count,error,forward:dir.y,dorsal:Math.asin(T.MathUtils.clamp(-dir.z,-1,1))*180/Math.PI};}
const results=[];for(const pair of [['p00487','p00490'],['p00691','p00693']])for(const id of pair)for(const finger of [2,3,4,5]){
const n=score.notes.find(n=>n.id===id),original={finger:n.finger,contactLift:n.contactLift};n.finger=finger;n.contactLift=finger===2?.0031:finger===5?.0034:.0027;rebuild();
const conflicts=score.notes.filter(m=>m.id!==n.id&&m.hand===n.hand&&m.finger===n.finger&&m.time<n.time+n.duration&&m.time+m.duration>n.time);
if(conflicts.length){results.push({pair,id,finger,rejected:'held-finger conflict',conflicts:conflicts.map(x=>x.id)});Object.assign(n,original);rebuild();continue;}
for(let iteration=0;iteration<4;iteration++){const samples=[.04,.25,.5,.75,.96].map(f=>sample(n,n.time+n.duration*f)),gaps=samples.map(s=>s.gap).filter(Number.isFinite);if(!gaps.length)break;const median=gaps.sort((a,b)=>a-b)[Math.floor(gaps.length/2)];n.contactLift=T.MathUtils.clamp(n.contactLift-median*.8,.0001,.016);}
const samples=Array.from({length:60},(_,i)=>sample(n,n.time+n.duration*(i+.5)/60));const row={pair,id,finger,contactLift:n.contactLift,maxErrorMm:Math.max(...samples.map(s=>s.error))*1000,skinMissing:samples.filter(s=>!s.count).length,minGapMm:Math.min(...samples.map(s=>s.gap))*1000,maxGapMm:Math.max(...samples.map(s=>s.gap))*1000,minForward:Math.min(...samples.map(s=>s.forward)),maxDorsal:Math.max(...samples.map(s=>s.dorsal))};row.passed=row.maxErrorMm<1&&!row.skinMissing&&row.minGapMm>-3&&row.maxGapMm<3&&row.minForward>-.15&&row.maxDorsal<60;results.push(row);Object.assign(n,original);rebuild();}
fs.writeFileSync('gap-search.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
